#!/usr/bin/env python3
"""Build the Atlassian API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Workflow Scheme': 'WF Scheme',
    'Application Role': 'App Role',
    'Application Props': 'App Props',
    'Connect Addons': 'Connect Addons',
    'Connect Migration': 'Connect Migr.',
    'Connect Service Reg': 'Connect Svc Reg',
    'Confluence Audit': 'Conf. Audit',
    'Confluence Settings': 'Conf. Settings',
    'Bitbucket Snippets': 'BB Snippets',
    'Bitbucket User': 'BB User',
}

LINES = [
    {
        "name": 'Jira — Core',
        "color": '#2684FF',
        "stations": [
        ('Issue', (270, 195)),
        ('Project', (430, 175)),
        ('Comment', (590, 165)),
        ('Attachment', (760, 175)),
        ('Field', (940, 200)),
        ],
    },
    {
        "name": 'Jira — Workflow',
        "color": '#0052CC',
        "stations": [
        ('Filter', (270, 310)),
        ('Dashboard', (430, 285)),
        ('Workflow', (610, 285)),
        ('Workflow Scheme', (810, 285)),
        ('Status', (1000, 310)),
        ],
    },
    {
        "name": 'Jira — Admin',
        "color": '#7B3FE4',
        "stations": [
        ('App', (270, 425)),
        ('Application Role', (450, 405)),
        ('Application Props', (640, 405)),
        ('Auditing', (820, 405)),
        ('User', (980, 425)),
        ],
    },
    {
        "name": 'Jira — Connect',
        "color": '#1E5BD0',
        "stations": [
        ('Connect Addons', (270, 540)),
        ('Connect App', (450, 515)),
        ('Connect Migration', (660, 515)),
        ('Connect Service Reg', (850, 540)),
        ],
    },
    {
        "name": 'Confluence',
        "color": '#0E9D6E',
        "stations": [
        ('Content', (270, 660)),
        ('Space', (430, 635)),
        ('User', (590, 635)),
        ('Group', (750, 635)),
        ('Search', (910, 660)),
        ],
    },
    {
        "name": 'Bitbucket',
        "color": '#E68B1F',
        "stations": [
        ('Repositories', (270, 770)),
        ('Pull Requests', (450, 745)),
        ('Workspaces', (640, 745)),
        ('Teams', (820, 770)),
        ],
    },
    {
        "name": 'Specialized',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Confluence Audit', (790, 815)),
        ('Confluence Settings', (905, 815)),
        ('Bitbucket Snippets', (790, 815)),
        ('Bitbucket User', (675, 815)),
        ],
    },
]

URL_OVERRIDES = {
    'Issue': 'https://apis.apis.io/apis/atlassian/atlassian-jira-issue-api/',
    'Project': 'https://apis.apis.io/apis/atlassian/atlassian-jira-project-api/',
    'Comment': 'https://apis.apis.io/apis/atlassian/atlassian-jira-comment-api/',
    'Attachment': 'https://apis.apis.io/apis/atlassian/atlassian-jira-attachment-api/',
    'Field': 'https://apis.apis.io/apis/atlassian/atlassian-jira-field-api/',
    'Filter': 'https://apis.apis.io/apis/atlassian/atlassian-jira-filter-api/',
    'Dashboard': 'https://apis.apis.io/apis/atlassian/atlassian-jira-dashboard-api/',
    'Workflow': 'https://apis.apis.io/apis/atlassian/atlassian-jira-workflow-api/',
    'Workflow Scheme': 'https://apis.apis.io/apis/atlassian/atlassian-jira-workflow-scheme-api/',
    'Status': 'https://apis.apis.io/apis/atlassian/atlassian-jira-status-api/',
    'App': 'https://apis.apis.io/apis/atlassian/atlassian-jira-app-api/',
    'Application Role': 'https://apis.apis.io/apis/atlassian/atlassian-jira-application-role-api/',
    'Application Props': 'https://apis.apis.io/apis/atlassian/atlassian-jira-application-properties-api/',
    'Auditing': 'https://apis.apis.io/apis/atlassian/atlassian-jira-auditing-api/',
    'User': 'https://apis.apis.io/apis/atlassian/atlassian-jira-user-api/',
    'Connect Addons': 'https://apis.apis.io/apis/atlassian/atlassian-jira-connect-addons-api/',
    'Connect App': 'https://apis.apis.io/apis/atlassian/atlassian-jira-connect-app-api/',
    'Connect Migration': 'https://apis.apis.io/apis/atlassian/atlassian-jira-connect-migration-api/',
    'Connect Service Reg': 'https://apis.apis.io/apis/atlassian/atlassian-jira-connect-service-registry-api/',
    'Content': 'https://apis.apis.io/apis/atlassian/atlassian-confluence-content-api/',
    'Space': 'https://apis.apis.io/apis/atlassian/atlassian-confluence-space-api/',
    'Group': 'https://apis.apis.io/apis/atlassian/atlassian-confluence-group-api/',
    'Search': 'https://apis.apis.io/apis/atlassian/atlassian-confluence-search-api/',
    'Repositories': 'https://apis.apis.io/apis/atlassian/atlassian-bitbucket-repositories-api/',
    'Pull Requests': 'https://apis.apis.io/apis/atlassian/atlassian-bitbucket-pull-requests-api/',
    'Workspaces': 'https://apis.apis.io/apis/atlassian/atlassian-bitbucket-workspaces-api/',
    'Teams': 'https://apis.apis.io/apis/atlassian/atlassian-bitbucket-teams-api/',
    'Confluence Audit': 'https://apis.apis.io/apis/atlassian/atlassian-confluence-audit-api/',
    'Confluence Settings': 'https://apis.apis.io/apis/atlassian/atlassian-confluence-settings-api/',
    'Bitbucket Snippets': 'https://apis.apis.io/apis/atlassian/atlassian-bitbucket-snippets-api/',
    'Bitbucket User': 'https://apis.apis.io/apis/atlassian/atlassian-bitbucket-user-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Atlassian API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: atlassian/openapi · github.com/api-evangelist/atlassian',
        out_dir=Path(__file__).resolve().parent,
        out_basename='atlassian-subway-map',
        provider_id='atlassian',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
