openapi: 3.1.0
info:
  title: Atlassian Admin Account Content States API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Content States
paths:
  /wiki/rest/api/content-states/delete:
    post:
      tags:
      - Content States
      summary: Atlassian Bulk Remove Content States From Content
      description: Creates a long running task that Removes content state from draft or published versions of pages specified.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**<br>Content Edit Permission for a content to have its state removed via this endpoint.
      operationId: atlassianBulkremovecontentstates
      security:
      - oAuthDefinitions:
        - write:confluence-content
      - basicAuth: []
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content:confluence
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/content-states/task/{taskId}:
    get:
      tags:
      - Content States
      summary: Atlassian Get Update on Long Running Task for Setting of Content State
      description: Get Status of long running task that was previously created to set or remove content states from content.<br>User must first create a task by passing in details to /wiki/rest/api/content-states PUT or DELETE endpoints.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**<br>Must have created long running task
      operationId: atlassianGettaskupdate
      security:
      - oAuthDefinitions:
        - read:confluence-content
      - basicAuth: []
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/space/{spaceKey}/state:
    get:
      tags:
      - Content States
      summary: Atlassian Get Space Suggested Content States
      description: Get content states that are suggested in the space.<br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Space view permission
      operationId: atlassianGetspacecontentstates
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-space.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-space.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:space.setting:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/space/{spaceKey}/state/settings:
    get:
      tags:
      - Content States
      summary: Atlassian Get Content State Settings for Space
      description: Get object describing whether content states are allowed at all, if custom content states or space content states<br>are restricted, and a list of space content states allowed for the space if they are not restricted.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Space admin permission
      operationId: atlassianGetcontentstatesettings
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-space.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-space.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:space.setting:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/space/{spaceKey}/state/content:
    get:
      tags:
      - Content States
      summary: Atlassian Get Content in Space With Given Content State
      description: Finds paginated content with <br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Space View Permission
      operationId: atlassianGetcontentswithstate
      security:
      - oAuthDefinitions:
        - read:confluence-content.all
      - basicAuth: []
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.all
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/content/{id}/state:
    get:
      tags:
      - Content States
      summary: Atlassian Get Content State
      description: Gets the current content state of the draft or current version of content. To specify the draft version, set<br>the parameter status to draft, otherwise archived or current will get the relevant published state.<br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to view the content.
      operationId: atlassianGetcontentstate
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
    put:
      tags:
      - Content States
      summary: Atlassian Set The Content State Of A Content And Publishes A New Version Of The Content
      description: Sets the content state of the content specified and creates a new version<br>(publishes the content without changing the body) of the content with the new state.<br><br>You may pass in either an id of a state, or the name and color of a desired new state.<br>If all 3 are passed in, id will be used.<br>If the name and color passed in already exist under the current user's existing custom states, the existing state will be reused.<br>If custom states are disabled in the space of[...]
      operationId: atlassianSetcontentstate
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content:confluence
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    delete:
      tags:
      - Content States
      summary: Atlassian Removes The Content State Of A Content And Publishes A New Version
      description: Removes the content state of the content specified and creates a new version<br>(publishes the content without changing the body) of the content with the new status.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianRemovecontentstate
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content:confluence
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
  /wiki/rest/api/content/{id}/state/available:
    get:
      tags:
      - Content States
      summary: Atlassian Gets Available Content States For Content
      description: Gets content states that are available for the content to be set as.<br>Will return all enabled Space Content States.<br>Will only return most the 3 most recently published custom content states to match UI editor list.<br>To get all custom content states, use the /content-states endpoint.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianGetavailablecontentstates
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
  /wiki/rest/api/content-states:
    put:
      tags:
      - Content States
      summary: Atlassian Bulk Set Content State Of Many Contents
      deprecated: true
      description: Creates a long running task that sets content state of draft or published versions of pages specified.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**<br>Content Edit Permission for a content to have its state set via this endpoint.
      operationId: atlassianBulksetcontentstates
      security:
      - oAuthDefinitions:
        - write:confluence-content
      - basicAuth: []
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content:confluence
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    get:
      tags:
      - Content States
      summary: Atlassian Get Custom Content States
      description: Get custom content states that authenticated user has created.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**<br>Must have user authentication.
      operationId: atlassianGetcustomcontentstates
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:user.property:confluence
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:user.property:confluence
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:user.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.