openapi: 3.2.0
info:
  title: Atlassian Webhooks API
  version: '1.0'
  description: 'Operations tagged Webhooks across 2 of this provider''s published API definitions: bitbucket-openapi-original.yml, jira-openapi-original.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: https://api.bitbucket.org/2.0
- url: https://your-domain.atlassian.net
tags:
- name: Webhooks
  description: 'Webhooks provide a way to configure Bitbucket Cloud to make requests to

    your server (or another external service) whenever certain events occur in

    Bitbucket Cloud.


    A webhook consists of:


    * A subject -- The resource that generates the events. Currently, this resource

    is the repository, user account, or team where you create the webhook.

    * One or more event -- The default event is a repository push, but you can

    select multiple events that can trigger the webhook.

    * A URL -- The endpoint where you want Bitbucket to send the event payloads

    when a matching event happens.


    There are two parts to getting a webhook to work: creating the webhook and

    triggering the webhook. After you create a webhook for an event, every time

    that event occurs, Bitbucket sends a payload request that describes the event

    to the specified URL. Thus, you can think of webhooks as a kind of

    notification system.


    Use webhooks to integrate applications with Bitbucket Cloud. The following

    use cases provides examples of when you would want to use webhooks:


    * Every time a user pushes commits in a repository, you may want to notify

    your CI server to start a build.

    * Every time a user pushes commits or creates a pull request, you may want to

    display a notification in your application.

    '
paths:
  /hook_events:
    get:
      tags:
      - Webhooks
      description: Returns the webhook resource or subject types on which webhooks can<br>be registered.<br><br>Each resource/subject type contains an `events` link that returns the<br>paginated list of specific events each individual subject type can<br>emit.<br><br>This endpoint is publicly accessible and does not require<br>authentication or scopes.
      summary: Atlassian Get A Webhook Resource
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      operationId: atlassianGetAWebhookResource
    servers:
    - url: https://api.bitbucket.org/2.0
  /hook_events/{subject_type}:
    get:
      tags:
      - Webhooks
      description: 'Returns a paginated list of all valid webhook events for the<br>specified entity.<br>**The team and user webhooks are deprecated, and you should use workspace instead.<br>For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**<br><br>This is public data that does not require any scopes or authentication.<br><br>NOTE: The example response is a truncated response object for the `workspace` `subject_type`.[...]'
      summary: Atlassian List Subscribable Webhook Types
      security:
      - oauth2: []
      - basic: []
      - api_key: []
      operationId: atlassianListSubscribableWebhookTypes
    servers:
    - url: https://api.bitbucket.org/2.0
  /rest/api/3/webhook:
    delete:
      deprecated: false
      description: Removes webhooks by ID. Only webhooks registered by the calling app are removed. If webhooks created by other apps are specified, they are ignored.<br><br>**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
      operationId: atlassianDeletewebhookbyid
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
        - manage:jira-webhook
      summary: Atlassian Delete Webhooks By Id
      tags:
      - Webhooks
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        - manage:jira-webhook
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:webhook:jira
        state: Beta
      x-atlassian-connect-scope: READ
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of the webhooks registered by the calling app.<br><br>**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
      operationId: atlassianGetdynamicwebhooksforapp
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
        - manage:jira-webhook
      summary: Atlassian Get Dynamic Webhooks For App
      tags:
      - Webhooks
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        - manage:jira-webhook
        state: Current
      - scheme: OAuth2
        scopes:
        - read:webhook:jira
        - read:jql:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Registers webhooks.<br><br>**NOTE:** for non-public OAuth apps, webhooks are delivered only if there is a match between the app owner and the user who registered a dynamic webhook.<br><br>**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
      operationId: atlassianRegisterdynamicwebhooks
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
        - manage:jira-webhook
      summary: Atlassian Register Dynamic Webhooks
      tags:
      - Webhooks
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        - manage:jira-webhook
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        - read:project:jira
        - write:webhook:jira
        state: Beta
      x-atlassian-connect-scope: READ
    servers:
    - url: https://your-domain.atlassian.net
  /rest/api/3/webhook/failed:
    get:
      deprecated: false
      description: Returns webhooks that have recently failed to be delivered to the requesting app after the maximum number of retries.<br><br>After 72 hours the failure may no longer be returned by this operation.<br><br>The oldest failure is returned first.<br><br>This method uses a cursor-based pagination. To request the next page use the failure time of the last webhook on the list as the `failedAfter` value or use the URL provided in `next`.<br><br>**[Permissions](#permissions) required:**[...]
      operationId: atlassianGetfailedwebhooks
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
        - manage:jira-webhook
      summary: Atlassian Get Failed Webhooks
      tags:
      - Webhooks
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        - manage:jira-webhook
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-details:jira
        - read:webhook:jira
        - read:comment.property:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-role:jira
        - read:epic:jira-software
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: READ
    servers:
    - url: https://your-domain.atlassian.net
  /rest/api/3/webhook/refresh:
    put:
      deprecated: false
      description: Extends the life of webhook. Webhooks registered through the REST API expire after 30 days. Call this operation to keep them alive.<br><br>Unrecognized webhook IDs (those that are not found or belong to other apps) are ignored.<br><br>**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
      operationId: atlassianRefreshwebhooks
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
        - manage:jira-webhook
      summary: Atlassian Extend Webhook Life
      tags:
      - Webhooks
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        - manage:jira-webhook
        state: Current
      - scheme: OAuth2
        scopes:
        - write:webhook:jira
        - read:webhook:jira
        state: Beta
      x-atlassian-connect-scope: READ
    servers:
    - url: https://your-domain.atlassian.net
components:
  securitySchemes:
    basic:
      type: http
      description: Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617) (Digest not supported). Note that Basic Auth is available only with username and app password as credentials.
      scheme: basic
    oauth2:
      type: oauth2
      description: OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749).
      flows:
        authorizationCode:
          authorizationUrl: https://bitbucket.org/site/oauth2/authorize
          tokenUrl: https://bitbucket.org/site/oauth2/access_token
          scopes:
            email: Read your account's primary email address
            account: Read your account information
            account:write: Read and modify your account information
            team: Read your team membership information
            team:write: Read and modify your team membership information
            repository: Read your repositories
            repository:write: Read and modify your repositories
            repository:admin: Administer your repositories
            repository:delete: Delete your repositories
            project: Read your workspace's project settings and read repositories contained within your workspace's projects
            project:admin: Read and modify settings for projects in your workspace
            pipeline: Access your repositories' build pipelines
            pipeline:write: Access and rerun your repositories' build pipelines
            pipeline:variable: Access your repositories' build pipelines and configure their variables
            runner: Access your workspaces/repositories' runners
            runner:write: Access and edit your workspaces/repositories' runners
            pullrequest: Read your repositories and their pull requests
            pullrequest:write: Read and modify your repositories and their pull requests
            webhook: Read and modify your repositories' webhooks
            issue: Read your repositories' issues
            issue:write: Read and modify your repositories' issues
            snippet: Read your snippets
            snippet:write: Read and modify your snippets
            wiki: Read and modify your repositories' wikis
    api_key:
      name: Authorization
      type: apiKey
      description: API Keys can be used as Basic HTTP Authentication credentials and provide a substitute for the account's actual username and password. API Keys are only available to team accounts and there is only 1 key per account. API Keys do not support scopes and have therefore access to all contents of the account.
      in: header
    OAuth2:
      description: OAuth2 scopes for Jira
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          scopes:
            delete:async-task:jira: Delete asynchronous task.
            delete:attachment:jira: Delete issue attachments.
            delete:avatar:jira: Delete system and custom avatars.
            delete:comment.property:jira: Delete issue comment properties.
            delete:comment:jira: Delete issue comments.
            delete:dashboard.property:jira: Delete dashboard properties.
            delete:dashboard:jira: Delete dashboards.
            delete:field-configuration-scheme:jira: Delete field configuration schemes.
            delete:field-configuration:jira: Delete field configurations.
            delete:field.option:jira: Delete field options.
            delete:field:jira: Delete fields.
            delete:filter.column:jira: Delete filter columns.
            delete:filter:jira: Delete filters.
            delete:group:jira: Delete user groups.
            delete:issue-link-type:jira: Delete issue link types.
            delete:issue-link:jira: Delete issue links.
            delete:issue-type-scheme:jira: Delete issue type schemes.
            delete:issue-type-screen-scheme:jira: Delete issue type screen schemes.
            delete:issue-type.property:jira: Delete issue type properties.
            delete:issue-type:jira: Delete issue types.
            delete:issue-worklog.property:jira: Delete issue worklog properties.
            delete:issue-worklog:jira: Delete issue worklogs.
            delete:issue.property:jira: Delete issue properties.
            delete:issue.remote-link:jira: Delete issue remote links.
            delete:issue:jira: Delete issues.
            delete:permission-scheme:jira: Delete permission schemes.
            delete:permission:jira: Delete permissions.
            delete:project-category:jira: Delete project categories.
            delete:project-role:jira: Delete project roles.
            delete:project-version:jira: Delete project versions.
            delete:project.avatar:jira: Delete project avatars.
            delete:project.component:jira: Delete project components.
            delete:project.property:jira: Delete project properties.
            delete:project:jira: Delete projects and their details, such as issue types, project lead, and avatars.
            delete:screen-scheme:jira: Delete screen schemes.
            delete:screen-tab:jira: Delete screen tabs.
            delete:screen:jira: Delete screens.
            delete:screenable-field:jira: Delete screenable fields.
            delete:user-configuration:jira: Delete user configurations.
            delete:user.property:jira: Delete user properties.
            delete:webhook:jira: Delete webhooks.
            delete:workflow-scheme:jira: Delete workflow schemes.
            delete:workflow.property:jira: Delete workflow properties.
            delete:workflow:jira: Delete workflows.
            manage:jira-configuration: Configure Jira settings that require the Jira administrators permission, for example, create projects and custom fields, view workflows, manage issue link types.
            manage:jira-project: Create and edit project settings and create new project-level objects, for example, versions, components.
            manage:jira-webhook: Manage Jira webhooks. Enables an OAuth app to register and unregister dynamic webhooks in Jira. It also provides for fetching of registered webhooks.
            read:application-role:jira: View application roles.
            read:attachment:jira: View issue attachments.
            read:audit-log:jira: View audit logs.
            read:avatar:jira: View system and custom avatars.
            read:comment.property:jira: View issue comment properties.
            read:comment:jira: View issue comments.
            read:custom-field-contextual-configuration:jira: Read custom field contextual configurations.
            read:dashboard.property:jira: View dashboard properties.
            read:dashboard:jira: View dashboards.
            read:field-configuration-scheme:jira: View field configuration schemes.
            read:field-configuration:jira: Read field configurations.
            read:field.default-value:jira: View field default values.
            read:field.option:jira: View field options.
            read:field.options:jira: Read field options.
            read:field:jira: View fields.
            read:filter.column:jira: View filter columns.
            read:filter.default-share-scope:jira: View filter default share scopes.
            read:filter:jira: View filters.
            read:group:jira: View user groups.
            read:instance-configuration:jira: View instance configurations.
            read:issue-details:jira: View issue details.
            read:issue-event:jira: Read issue events.
            read:issue-field-values:jira: View issue field valueses.
            read:issue-link-type:jira: View issue link types.
            read:issue-link:jira: View issue links.
            read:issue-meta:jira: View issue meta.
            read:issue-security-level:jira: View issue security levels.
            read:issue-security-scheme:jira: View issue security schemes.
            read:issue-status:jira: View issue statuses.
            read:issue-type-hierarchy:jira: Read issue type hierarchies.
            read:issue-type-scheme:jira: View issue type schemes.
            read:issue-type-screen-scheme:jira: View issue type screen schemes.
            read:issue-type.property:jira: View issue type properties.
            read:issue-type:jira: View issue types.
            read:issue-worklog.property:jira: View issue worklog properties.
            read:issue-worklog:jira: View issue worklogs.
            read:issue.changelog:jira: View issue changelogs.
            read:issue.property:jira: View issue properties.
            read:issue.remote-link:jira: View issue remote links.
            read:issue.time-tracking:jira: View issue time trackings.
            read:issue.transition:jira: View issue transitions.
            read:issue.vote:jira: View issue votes.
            read:issue.votes:jira: View issue voteses.
            read:issue.watcher:jira: View issue watchers.
            read:issue:jira: View issues.
            read:jira-expressions:jira: View jira expressions.
            read:jira-user: View user information in Jira that you have access to, including usernames, email addresses, and avatars.
            read:jira-work: Read project and issue data. Search for issues and objects associated with issues (such as attachments and worklogs).
            read:jql:jira: View JQL.
            read:label:jira: View labels.
            read:license:jira: View licenses.
            read:notification-scheme:jira: View notification schemes.
            read:permission-scheme:jira: View permission schemes.
            read:permission:jira: View permissions.
            read:priority:jira: View priorities.
            read:project-category:jira: View project categories.
            read:project-role:jira: View project roles.
            read:project-type:jira: View project types.
            read:project-version:jira: View project versions.
            read:project.avatar:jira: Read project avatars.
            read:project.component:jira: View project components.
            read:project.email:jira: View project emails.
            read:project.feature:jira: Read project features.
            read:project.property:jira: View project properties.
            read:project:jira: View projects.
            read:resolution:jira: View resolutions.
            read:role:jira: View roles.
            read:screen-field:jira: View screen fields.
            read:screen-scheme:jira: View screen schemes.
            read:screen-tab:jira: View screen tabs.
            read:screen:jira: View screens.
            read:screenable-field:jira: View screenable fields.
            read:status:jira: View statuses.
            read:user-configuration:jira: View user configurations.
            read:user.columns:jira: View user columnses.
            read:user.property:jira: View user properties.
            read:user:jira: View users.
            read:webhook:jira: View webhooks.
            read:workflow-scheme:jira: View workflow schemes.
            read:workflow.property:jira: View workflow properties.
            read:workflow:jira: View workflows.
            send:notification:jira: Send notifications.
            validate:jql:jira: Validate JQL.
            write:attachment:jira: Create and update issue attachments.
            write:avatar:jira: Create and update system and custom avatars.
            write:comment.property:jira: Create and update issue comment properties.
            write:comment:jira: Create and update issue comments.
            write:custom-field-contextual-configuration:jira: Save custom field contextual configurations.
            write:dashboard.property:jira: Create and update dashboard properties.
            write:dashboard:jira: Create and update dashboards.
            write:field-configuration-scheme:jira: Create and update field configuration schemes.
            write:field-configuration:jira: Save field configurations.
            write:field.default-value:jira: Create and update field default values.
            write:field.option:jira: Create and update field options.
            write:field:jira: Create and update fields.
            write:filter.column:jira: Create and update filter columns.
            write:filter.default-share-scope:jira: Create and update filter default share scopes.
            write:filter:jira: Create and update filters.
            write:group:jira: Create and update user groups.
            write:instance-configuration:jira: Create and update instance configurations.
            write:issue-link-type:jira: Create and update issue link types.
            write:issue-link:jira: Create and update issue links.
            write:issue-type-scheme:jira: Create and update issue type schemes.
            write:issue-type-screen-scheme:jira: Create and update issue type screen schemes.
            write:issue-type.property:jira: Create and update issue type properties.
            write:issue-type:jira: Create and update issue types.
            write:issue-worklog.property:jira: Create and update issue worklog properties.
            write:issue-worklog:jira: Create and update issue worklogs.
            write:issue.property:jira: Create and update issue properties.
            write:issue.remote-link:jira: Create and update issue remote links.
            write:issue.time-tracking:jira: Create and update issue time trackings.
            write:issue.vote:jira: Create and update issue votes.
            write:issue.watcher:jira: Create and update issue watchers.
            write:issue:jira: Create and update issues.
            write:jira-work: Create and edit issues in Jira, post comments, create worklogs, and delete issues.
            write:permission-scheme:jira: Create and update permission schemes.
            write:permission:jira: Create and update permissions.
            write:project-category:jira: Create and update project categories.
            write:project-role:jira: Create and update project roles.
            write:project-version:jira: Create and update project versions.
            write:project.avatar:jira: Create and update project avatars.
            write:project.component:jira: Create and update project components.
            write:project.email:jira: Create and update project emails.
            write:project.feature:jira: Save project features.
            write:project.property:jira: Create and update project properties.
            write:project:jira: Create and update projects.
            write:screen-scheme:jira: Create and update screen schemes.
            write:screen-tab:jira: Create and update screen tabs.
            write:screen:jira: Create and update screens.
            write:screenable-field:jira: Create and update screenable fields.
            write:user-configuration:jira: Create and update user configurations.
            write:user.property:jira: Create and update user properties.
            write:webhook:jira: Create and update webhooks.
            write:workflow-scheme:jira: Create and update workflow schemes.
            write:workflow.property:jira: Create and update workflow properties.
            write:workflow:jira: Create and update workflows.
          tokenUrl: https://auth.atlassian.com/oauth/token
      type: oauth2
    basicAuth:
      description: You can access this resource via basic auth.
      scheme: basic
      type: http
x-refined-from:
- bitbucket-openapi-original.yml
- jira-openapi-original.yml
