openapi: 3.2.0
info:
  title: Atlassian Pullrequests API
  version: '2.0'
  contact:
    name: Bitbucket Support
    url: https://support.atlassian.com/bitbucket-cloud/
    email: support@bitbucket.org
  termsOfService: https://www.atlassian.com/legal/customer-agreement
  description: 'Operations tagged Pullrequests across 2 of this provider''s published API definitions: bitbucket-openapi-original.yml, bitbucket-swagger.json. Each path carries the servers of the definition it was published in.'
servers:
- url: https://api.bitbucket.org/2.0
tags:
- name: Pull Requests
paths:
  /pullrequests/{selected_user}:
    get:
      tags:
      - Pull Requests
      description: 'Returns all pull requests authored by the specified user.


        By default only open pull requests are returned. This can be controlled

        using the `state` query parameter. To retrieve pull requests that are

        in one of multiple states, repeat the `state` parameter for each

        individual state.


        This endpoint also supports filtering and sorting of the results. See

        filtering and sorting for more details.'
      summary: Atlassian List Pull Requests For A User
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      operationId: atlassianListPullRequestsForAUser
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commit/{commit}/pullrequests:
    get:
      tags:
      - Pull Requests
      summary: Atlassian List Pull Requests That Contain A Commit
      description: Returns a paginated list of all pull requests as part of which this commit was reviewed. Pull Request Commit Links app must be installed first before using this API; installation automatically occurs when 'Go to pull request' is clicked from the web interface for a commit's details.
      operationId: atlassianGetpullrequestsforcommit
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/default-reviewers:
    get:
      tags:
      - Pull Requests
      description: 'Returns the repository''s default reviewers.


        These are the users that are automatically added as reviewers on every

        new pull request that is created. To obtain the repository''s default reviewers

        as well as the default reviewers inherited from the project, use the

        effective-default-reveiwers endpoint.'
      summary: Atlassian List Default Reviewers
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListDefaultReviewers
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/default-reviewers/{target_username}:
    delete:
      tags:
      - Pull Requests
      description: Removes a default reviewer from the repository.
      summary: Atlassian Remove A User From The Default Reviewers
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - admin:repository:bitbucket
      operationId: atlassianRemoveAUserFromTheDefaultReviewers
    get:
      tags:
      - Pull Requests
      description: 'Returns the specified reviewer.


        This can be used to test whether a user is among the repository''s

        default reviewers list. A 404 indicates that that specified user is not

        a default reviewer.'
      summary: Atlassian Get A Default Reviewer
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetADefaultReviewer
    put:
      tags:
      - Pull Requests
      description: 'Adds the specified user to the repository''s list of default

        reviewers.


        This method is idempotent. Adding a user a second time has no effect.'
      summary: Atlassian Add A User To The Default Reviewers
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - admin:repository:bitbucket
      operationId: atlassianAddAUserToTheDefaultReviewers
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/effective-default-reviewers:
    get:
      tags:
      - Pull Requests
      description: 'Returns the repository''s effective default reviewers. This includes both default

        reviewers defined at the repository level as well as those inherited from its project.


        These are the users that are automatically added as reviewers on every

        new pull request that is created.'
      summary: Atlassian List Effective Default Reviewers
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListEffectiveDefaultReviewers
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests:
    get:
      tags:
      - Pull Requests
      description: 'Returns all pull requests on the specified repository.


        By default only open pull requests are returned. This can be controlled

        using the `state` query parameter. To retrieve pull requests that are

        in one of multiple states, repeat the `state` parameter for each

        individual state.


        This endpoint also supports filtering and sorting of the results. See

        filtering and sorting for more details.'
      summary: Atlassian List Pull Requests
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListPullRequests
    post:
      tags:
      - Pull Requests
      description: 'Creates a new pull request where the destination repository is

        this repository and the author is the authenticated user.


        The minimum required fields to create a pull request are `title` and

        `source`, specified by a branch name.


        ```

        curl https://api.bitbucket.org/2.0/repositories/my-workspace/my-repository/pullrequests \

        -u my-username:my-password \

        --request POST \

        --header ''Content-Type: application/json'' \

        --data ''{

        "title": "My Title",

        "source": {

        "branch": {

        "name": "staging"

        }

        }

        }''

        ```


        If the pull request''s `destination` is not specified, it will default

        to the `repository.mainbranch`. To open a pull request to a

        different branch, say from a feature branch to a staging branch,

        specify a `destination` (same format as the `source`):


        ```

        {

        "title": "My Title",

        "source": {

        "branch": {

        "name": "my-feature-branch"

        }

        },

        "destination": {

        "branch": {

        "name": "staging"

        }

        }

        }

        ```


        Reviewers can be specified by adding an array of user objects as the

        `reviewers` property.


        ```

        {

        "title": "My Title",

        "source": {

        "branch": {

        "name": "my-feature-branch"

        }

        },

        "reviewers": [

        {

        "uuid": "{504c3b62-8120-4f0c-a7bc-87800b9d6f70}"

        }

        ]

        }

        ```


        Other fields:


        * `description` - a string

        * `close_source_branch` - boolean that specifies if the source branch should be closed upon merging'
      summary: Atlassian Create A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianCreateAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/activity:
    get:
      tags:
      - Pull Requests
      description: Returns a paginated list of the pull request's activity log.
      summary: Atlassian List A Pull Request Activity Log
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListAPullRequestActivityLog
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}:
    get:
      tags:
      - Pull Requests
      description: Returns the specified pull request.
      summary: Atlassian Get A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetAPullRequest
    put:
      tags:
      - Pull Requests
      description: 'Mutates the specified pull request.


        This can be used to change the pull request''s branches or description.


        Only open pull requests can be mutated.'
      summary: Atlassian Update A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianUpdateAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/activity:
    get:
      tags:
      - Pull Requests
      description: Returns a paginated list of the pull request's activity log.
      summary: Atlassian List A Pull Request Activity Log
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: getRepositoriesByWorkspaceByRepoSlugPullrequestsByPullRequestIdActivity
      x-operation-id-source: normalized
      x-operation-id-original: atlassianListAPullRequestActivityLog
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve:
    delete:
      tags:
      - Pull Requests
      description: 'Redact the authenticated user''s approval of the specified pull

        request.'
      summary: Atlassian Unapprove A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - write:pullrequest:bitbucket
      operationId: atlassianUnapproveAPullRequest
    post:
      tags:
      - Pull Requests
      description: Approve the specified pull request as the authenticated user.
      summary: Atlassian Approve A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianApproveAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments:
    get:
      tags:
      - Pull Requests
      description: 'Returns a paginated list of the pull request''s comments.


        This includes both global, inline comments and replies.


        The default sorting is oldest to newest and can be overridden with

        the `sort` query parameter.


        This endpoint also supports filtering and sorting of the results. See

        filtering and sorting for more

        details.'
      summary: Atlassian List Comments On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListCommentsOnAPullRequest
    post:
      tags:
      - Pull Requests
      description: 'Creates a new pull request comment.


        Returns the newly created pull request comment.'
      summary: Atlassian Create A Comment On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianCreateACommentOnAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}:
    delete:
      tags:
      - Pull Requests
      description: Deletes a specific pull request comment.
      summary: Atlassian Delete A Comment On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianDeleteACommentOnAPullRequest
    get:
      tags:
      - Pull Requests
      description: Returns a specific pull request comment.
      summary: Atlassian Get A Comment On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetACommentOnAPullRequest
    put:
      tags:
      - Pull Requests
      description: Updates a specific pull request comment.
      summary: Atlassian Update A Comment On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianUpdateACommentOnAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}/resolve:
    delete:
      tags:
      - Pull Requests
      description: Needs a more full description created.
      summary: Atlassian Reopen A Comment Thread
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianReopenACommentThread
    post:
      tags:
      - Pull Requests
      description: Needs a more full description created.
      summary: Atlassian Resolve A Comment Thread
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianResolveACommentThread
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/commits:
    get:
      tags:
      - Pull Requests
      description: 'Returns a paginated list of the pull request''s commits.


        These are the commits that are being merged into the destination

        branch when the pull requests gets accepted.'
      summary: Atlassian List Commits On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListCommitsOnAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/decline:
    post:
      tags:
      - Pull Requests
      description: Declines the pull request.
      summary: Atlassian Decline A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianDeclineAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diff:
    get:
      tags:
      - Pull Requests
      description: 'Redirects to the repository diff

        with the revspec that corresponds to the pull request.'
      summary: Atlassian List Changes In A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListChangesInAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diffstat:
    get:
      tags:
      - Pull Requests
      description: 'Redirects to the repository diffstat

        with the revspec that corresponds to the pull request.'
      summary: Atlassian Get The Diff Stat For A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetTheDiffStatForAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge:
    post:
      tags:
      - Pull Requests
      description: Merges the pull request.
      summary: Atlassian Merge A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianMergeAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge/task-status/{task_id}:
    get:
      tags:
      - Pull Requests
      description: 'When merging a pull request takes too long, the client receives a

        task ID along with a 202 status code. The task ID can be used in a call

        to this endpoint to check the status of a merge task.


        ```

        curl -X GET https://api.bitbucket.org/2.0/repositories/atlassian/bitbucket/pullrequests/2286/merge/task-status/

        ```


        If the merge task is not yet finished, a PENDING status will be returned.


        ```

        HTTP/2 200

        {

        "task_status": "PENDING",

        "self": {

        "href": "https://api.bitbucket.org/2.0/repositories/atlassian/bitbucket/pullrequests/2286/merge/task-status/"

        }

        }

        }

        ```


        If the merge was successful, a SUCCESS status will be returned.


        ```

        HTTP/2 200

        {

        "task_status": "SUCCESS",

        "self": {

        "href": "https://api.bitbucket.org/2.0/repositories/atlassian/bitbucket/pullrequests/2286/merge/task-status/"

        }

        },

        "merge_result":

        }

        ```


        If the merge task failed, an error will be returned.


        ```

        {

        "type": "error",

        "error": {

        "message": ""

        }

        }

        ```'
      summary: Atlassian Get The Merge Task Status For A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetTheMergeTaskStatusForAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/patch:
    get:
      tags:
      - Pull Requests
      description: 'Redirects to the repository patch

        with the revspec that corresponds to pull request.'
      summary: Atlassian Get The Patch For A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetThePatchForAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/request-changes:
    delete:
      tags:
      - Pull Requests
      description: Needs a more full description created.
      summary: Atlassian Remove Change Request For A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - write:pullrequest:bitbucket
      operationId: atlassianRemoveChangeRequestForAPullRequest
    post:
      tags:
      - Pull Requests
      description: Needs a more full description created.
      summary: Atlassian Request Changes For A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianRequestChangesForAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/tasks:
    get:
      tags:
      - Pull Requests
      description: 'Returns a paginated list of the pull request''s tasks.


        This endpoint supports filtering and sorting of the results by the ''task'' field.

        See filtering and sorting for more details.'
      summary: Atlassian List Tasks On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListTasksOnAPullRequest
    post:
      tags:
      - Pull Requests
      description: 'Creates a new pull request task.


        Returns the newly created pull request task.


        Tasks can optionally be created in relation to a comment specified by the comment''s ID which

        will cause the task to appear below the comment on a pull request when viewed in Bitbucket.'
      summary: Atlassian Create A Task On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianCreateATaskOnAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/tasks/{task_id}:
    delete:
      tags:
      - Pull Requests
      description: Deletes a specific pull request task.
      summary: Atlassian Delete A Task On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianDeleteATaskOnAPullRequest
    get:
      tags:
      - Pull Requests
      description: Returns a specific pull request task.
      summary: Atlassian Get A Task On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetATaskOnAPullRequest
    put:
      tags:
      - Pull Requests
      description: Updates a specific pull request task.
      summary: Atlassian Update A Task On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianUpdateATaskOnAPullRequest
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/conflicts:
    get:
      tags:
      - Pull Requests
      description: 'Redirects to the repository file conflicts

        with the revspec that corresponds to the pull request.'
      summary: Get file conflicts for a pull request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
      operationId: getRepositoriesByWorkspaceByRepoSlugPullrequestsByPullRequestIdConflicts
      x-operation-id-source: derived
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/mergeability/checks:
    get:
      tags:
      - Pull Requests
      description: 'Returns the mergeability checks Bitbucket performs for this pull request, and whether each one

        currently allows the pull request to be merged - simulating what the merge endpoint checks before

        actually merging.


        Checks cover pull request state, the current user''s merge permissions, Git conflicts, configured

        standard and custom merge checks, and merge queue status when available. Each check''s `blocking`

        attribute indicates whether it currently prevents merging. A failed check does not necessarily block a merge.


        `pullrequest_state_check`, `current_user_permission_check`, and `git_mergeability_check` cover state,

        permission, and Git eligibility. One `standard_merge_check` is included per configured branch/merge

        restriction, and one `custom_pre_merge_check`/`custom_on_merge_check` per activated custom check - both

        omitted entirely, not reported as passing, when not configured. Not exhaustive: conditions Bitbucket can''t

        evaluate without attempting the merge (e.g. dependency-merge requirements) aren''t included. See

        `PullRequestMergeabilityCheckSchema` for per-check fields, and `q` below to exclude the checks that

        are expensive to evaluate.


        For repositories with merge queues enabled, a `merge_queue_check` reports queue availability and

        whether the pull request is already queued. It is included for open, non-draft pull requests when the

        destination branch requires queueing, and for already-queued pull requests with a configured queue.

        The check is omitted when no merge queue is configured for the destination branch. When the check is

        present, `merge_queue` contains that configured queue''s UUID, name and state. Already-queued pull requests

        return their blocking state check and any applicable queue check, without evaluating Git or other merge checks.

        A failed queue configuration read fails the whole request with `500`, as for custom merge check results.


        Returns `500` if custom merge checks are configured but their results aren''t currently retrievable,

        since the real merge action requires them too and would fail the same way.'
      summary: List pull request mergeability checks
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
      operationId: getRepositoriesByWorkspaceByRepoSlugPullrequestsByPullRequestIdMergeabilityChecks
      x-operation-id-source: derived
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/statuses:
    get:
      tags:
      - Pull Requests
      description: 'Returns all statuses (e.g. build results) for the given pull

        request.'
      summary: List commit statuses for a pull request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
      operationId: getRepositoriesByWorkspaceByRepoSlugPullrequestsByPullRequestIdStatuses
      x-operation-id-source: derived
    servers:
    - url: https://api.bitbucket.org/2.0
  /workspaces/{workspace}/pullrequests/{selected_user}:
    get:
      tags:
      - Pull Requests
      description: 'Returns all workspace pull requests authored by the specified user.


        By default only open pull requests are returned. This can be controlled

        using the `state` query parameter. To retrieve pull requests that are

        in one of multiple states, repeat the `state` parameter for each

        individual state.


        This endpoint also supports filtering and sorting of the results. See

        filtering and sorting for more details.'
      summary: List workspace pull requests for a user
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      x-atlassian-auth-types:
      - api-token
      operationId: getWorkspacesByWorkspacePullrequestsBySelectedUser
      x-operation-id-source: derived
    servers:
    - url: https://api.bitbucket.org/2.0
components:
  securitySchemes:
    basic:
      type: http
      description: Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617) (Digest not supported). Note that Basic Auth is available only with username and app password as credentials.
      scheme: basic
    oauth2:
      type: oauth2
      description: OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749).
      flows:
        authorizationCode:
          authorizationUrl: https://bitbucket.org/site/oauth2/authorize
          tokenUrl: https://bitbucket.org/site/oauth2/access_token
          scopes:
            email: Read your account's primary email address
            account: Read your account information
            account:write: Read and modify your account information
            team: Read your team membership information
            team:write: Read and modify your team membership information
            repository: Read your repositories
            repository:write: Read and modify your repositories
            repository:admin: Administer your repositories
            repository:delete: Delete your repositories
            project: Read your workspace's project settings and read repositories contained within your workspace's projects
            project:admin: Read and modify settings for projects in your workspace
            pipeline: Access your repositories' build pipelines
            pipeline:write: Access and rerun your repositories' build pipelines
            pipeline:variable: Access your repositories' build pipelines and configure their variables
            runner: Access your workspaces/repositories' runners
            runner:write: Access and edit your workspaces/repositories' runners
            pullrequest: Read your repositories and their pull requests
            pullrequest:write: Read and modify your repositories and their pull requests
            webhook: Read and modify your repositories' webhooks
            issue: Read your repositories' issues
            issue:write: Read and modify your repositories' issues
            snippet: Read your snippets
            snippet:write: Read and modify your snippets
            wiki: Read and modify your repositories' wikis
    api_key:
      name: Authorization
      type: apiKey
      description: API Keys can be used as Basic HTTP Authentication credentials and provide a substitute for the account's actual username and password. API Keys are only available to team accounts and there is only 1 key per account. API Keys do not support scopes and have therefore access to all contents of the account.
      in: header
x-refined-from:
- bitbucket-openapi-original.yml
- bitbucket-swagger.json
