openapi: 3.1.0
info:
  title: Atlassian Admin Account Workflow Scheme Drafts API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Workflow Scheme Drafts
paths:
  /rest/api/3/workflowscheme/{id}/createdraft:
    post:
      deprecated: false
      description: Create a draft workflow scheme from an active workflow scheme, by copying the active workflow scheme. Note that an active workflow scheme can only have one draft workflow scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreateworkflowschemedraftfromparent
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:group:jira
        - read:issue-security-level:jira
        - read:project-role:jira
        - read:screen:jira
        - read:status:jira
        - read:user:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        - write:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}/draft:
    delete:
      deprecated: false
      description: Deletes a draft workflow scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteworkflowschemedraft
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:workflow-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: 'Returns the draft workflow scheme for an active workflow scheme. Draft workflow schemes allow changes to be made to the active workflow schemes: When an active workflow scheme is updated, a draft copy is created. The draft is modified, then the changes in the draft are copied back to the active workflow scheme. See [Configuring workflow schemes](https://confluence.atlassian.com/x/tohKLg) for more information.  <br>Note that:<br><br> *  Only active workflow schemes can have dr[...]'
      operationId: atlassianGetworkflowschemedraft
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:group:jira
        - read:issue-security-level:jira
        - read:project-role:jira
        - read:screen:jira
        - read:status:jira
        - read:user:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates a draft workflow scheme. If a draft workflow scheme does not exist for the active workflow scheme, then a draft is created. Note that an active workflow scheme can only have one draft workflow scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdateworkflowschemedraft
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:group:jira
        - read:issue-security-level:jira
        - read:project-role:jira
        - read:screen:jira
        - read:status:jira
        - read:user:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        - write:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}/draft/default:
    delete:
      deprecated: false
      description: Resets the default workflow for a workflow scheme's draft. That is, the default workflow is set to Jira's system workflow (the *jira* workflow).<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeletedraftdefaultworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Draft Default Workflow
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns the default workflow for a workflow scheme's draft. The default workflow is the workflow that is assigned any issue types that have not been mapped to any other workflow. The default workflow has *All Unassigned Issue Types* listed in its issue types for the workflow scheme in Jira.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetdraftdefaultworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Draft Default Workflow
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - read:workflow:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Sets the default workflow for a workflow scheme's draft.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatedraftdefaultworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Draft Default Workflow
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}/draft/issuetype/{issueType}:
    delete:
      deprecated: false
      description: Deletes the issue type-workflow mapping for an issue type in a workflow scheme's draft.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteworkflowschemedraftissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Workflow For Issue Type In Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns the issue type-workflow mapping for an issue type in a workflow scheme's draft.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetworkflowschemedraftissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Workflow For Issue Type In Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:issue-type:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Sets the workflow for an issue type in a workflow scheme's draft.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianSetworkflowschemedraftissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Set Workflow For Issue Type In Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}/draft/publish:
    post:
      deprecated: false
      description: Publishes a draft workflow scheme.<br><br>Where the draft workflow includes new workflow statuses for an issue type, mappings are provided to update issues with the original workflow status to the new workflow status.<br><br>This operation is [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain updates.<br><br>**[Permissions](#permissions) required:** *Administer Jir[...]
      operationId: atlassianPublishdraftworkflowscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Publish Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}/draft/workflow:
    delete:
      deprecated: false
      description: Deletes the workflow-issue type mapping for a workflow in a workflow scheme's draft.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeletedraftworkflowmapping
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Issue Types For Workflow In Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:workflow-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns the workflow-issue type mappings for a workflow scheme's draft.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetdraftworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Types For Workflows In Draft Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:issue-type:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Sets the issue types for a workflow in a workflow scheme's draft. The workflow can also be set as the default workflow for the draft workflow scheme. Unmapped issues types are mapped to the default workflow.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatedraftworkflowmapping
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Set Issue Types For Workflow In Workflow Scheme
      tags:
      - Workflow Scheme Drafts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.