openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Attachments API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Attachments
paths:
  /rest/api/3/attachment/content/{id}:
    get:
      deprecated: false
      description: Returns the contents of an attachment. A `Range` header can be set to define a range of bytes within the attachment to download. See the [HTTP Range header standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) for details.<br><br>To return a thumbnail of the attachment, use [Get attachment thumbnail](#api-rest-api-3-attachment-thumbnail-id-get).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** For the issu[...]
      operationId: atlassianGetattachmentcontent
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Attachment Content
      tags:
      - Issue Attachments
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:attachment:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/attachment/meta:
    get:
      deprecated: false
      description: Returns the attachment settings, that is, whether attachments are enabled and the maximum attachment size allowed.<br><br>Note that there are also [project permissions](https://confluence.atlassian.com/x/yodKLg) that restrict whether users can create and delete attachments.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianGetattachmentmeta
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Jira Attachment Settings
      tags:
      - Issue Attachments
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:instance-configuration:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/attachment/thumbnail/{id}:
    get:
      deprecated: false
      description: Returns the thumbnail of an attachment.<br><br>To return the attachment contents, use [Get attachment content](#api-rest-api-3-attachment-content-id-get).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** For the issue containing the attachment:<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-level security](https://confluence.at[...]
      operationId: atlassianGetattachmentthumbnail
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Attachment Thumbnail
      tags:
      - Issue Attachments
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:attachment:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/attachment/{id}:
    delete:
      deprecated: false
      description: Deletes an attachment from an issue.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** For the project holding the issue containing the attachment:<br><br> *  *Delete own attachments* [project permission](https://confluence.atlassian.com/x/yodKLg) to delete an attachment created by the calling user.<br> *  *Delete all attachments* [project permission](https://confluence.atlassian.com/x/yodKLg) to delete an attachment created by[...]
      operationId: atlassianRemoveattachment
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Delete Attachment
      tags:
      - Issue Attachments
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:attachment:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns the metadata for an attachment. Note that the attachment itself is not returned.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
      operationId: atlassianGetattachment
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Attachment Metadata
      tags:
      - Issue Attachments
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:attachment:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/attachment/{id}/expand/human:
    get:
      deprecated: false
      description: Returns the metadata for the contents of an attachment, if it is an archive, and metadata for the attachment itself. For example, if the attachment is a ZIP archive, then information about the files in the archive is returned and metadata for the ZIP archive. Currently, only the ZIP archive format is supported.<br><br>Use this operation to retrieve data that is presented to the user, as this operation returns the metadata for the attachment itself, such as the attachment's ID [...]
      operationId: atlassianExpandattachmentforhumans
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get All Metadata For An Expanded Attachment
      tags:
      - Issue Attachments
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:attachment:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: READ
  /rest/api/3/attachment/{id}/expand/raw:
    get:
      deprecated: false
      description: Returns the metadata for the contents of an attachment, if it is an archive. For example, if the attachment is a ZIP archive, then information about the files in the archive is returned. Currently, only the ZIP archive format is supported.<br><br>Use this operation if you are processing the data without presenting it to the user, as this operation only returns the metadata for the contents of the attachment. Otherwise, to retrieve data to present to the user, use [ Get all met[...]
      operationId: atlassianExpandattachmentformachines
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Contents Metadata For An Expanded Attachment
      tags:
      - Issue Attachments
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:attachment:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: READ
  /rest/api/3/issue/{issueIdOrKey}/attachments:
    post:
      deprecated: false
      description: 'Adds one or more attachments to an issue. Attachments are posted as multipart/form-data ([RFC 1867](https://www.ietf.org/rfc/rfc1867.txt)).<br><br>Note that:<br><br> *  The request must have a `X-Atlassian-Token: no-check` header, if not it is blocked. See [Special headers](#special-request-headers) for more information.<br> *  The name of the multipart/form-data parameter that contains the attachments must be `file`.<br><br>The following examples upload a file called *myfile[...]'
      operationId: atlassianAddattachment
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Add Attachment
      tags:
      - Issue Attachments
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user:jira
        - write:attachment:jira
        - read:attachment:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.