openapi: 3.1.0
info:
  title: Atlassian Admin Account User Search API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: User Search
paths:
  /rest/api/3/user/assignable/multiProjectSearch:
    get:
      deprecated: false
      description: Returns a list of users who can be assigned issues in one or more projects. The list may be restricted to users whose attributes match a string.<br><br>This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that can be assigned issues in the projects. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who can be assigned [...]
      operationId: atlassianFindbulkassignableusers
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      - {}
      summary: Atlassian Find Users Assignable To Projects
      tags:
      - User Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:project:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/user/assignable/search:
    get:
      deprecated: false
      description: Returns a list of users that can be assigned to an issue. Use this operation to find the list of users who can be assigned to:<br><br> *  a new issue, by providing the `projectKeyOrId`.<br> *  an updated issue, by providing the `issueKey`.<br> *  to an issue during a transition (workflow action), by providing the `issueKey` and the transition id in `actionDescriptorId`. You can obtain the IDs of an issue's valid transitions using the `transitions` option in the `expand` parame[...]
      operationId: atlassianFindassignableusers
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      - {}
      summary: Atlassian Find Users Assignable To Issues
      tags:
      - User Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue:jira
        - read:project:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/user/permission/search:
    get:
      deprecated: false
      description: Returns a list of users who fulfill these criteria:<br><br> *  their user attributes match a search string.<br> *  they have a set of permissions for a project or issue.<br><br>If no search string is provided, a list of all users with the permissions is returned.<br><br>This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that match the search string and have permission for[...]
      operationId: atlassianFinduserswithallpermissions
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      - {}
      summary: Atlassian Find Users With Permissions
      tags:
      - User Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue:jira
        - read:project:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/user/picker:
    get:
      deprecated: false
      description: Returns a list of users whose attributes match the query term. The returned object includes the `html` field where the matched query term is highlighted with the HTML strong tag. A list of account IDs can be provided to exclude users from the results.<br><br>This operation takes the users in the range defined by `maxResults`, up to the thousandth user, and then returns only the users from that range that match the query term. This means the operation usually returns fewer user[...]
      operationId: atlassianFindusersforpicker
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      - {}
      summary: Atlassian Find Users For Picker
      tags:
      - User Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/user/search:
    get:
      deprecated: false
      description: Returns a list of active users that match the search string and property.<br><br>This operation first applies a filter to match the search string and property, and then takes the filtered users in the range defined by `startAt` and `maxResults`, up to the thousandth user. To get all the users who match the search string and property, use [Get all users](#api-rest-api-3-users-search-get) and filter the records in your code.<br><br>This operation can be accessed anonymously.<br>[...]
      operationId: atlassianFindusers
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      - {}
      summary: Atlassian Find Users
      tags:
      - User Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user:jira
        - read:user.property:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/user/search/query:
    get:
      deprecated: false
      description: Finds users with a structured query and returns a [paginated](#pagination) list of user details.<br><br>This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that match the structured query. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who match the structured query, use [Get all users](#api-rest-api-3-users-search[...]
      operationId: atlassianFindusersbyquery
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      summary: Atlassian Find Users By Query
      tags:
      - User Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:comment:jira
        - read:issue:jira
        - read:issue.vote:jira
        - read:issue.watcher:jira
        - read:project:jira
        - read:user:jira
        - read:user.property:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/user/search/query/key:
    get:
      deprecated: false
      description: Finds users with a structured query and returns a [paginated](#pagination) list of user keys.<br><br>This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that range that match the structured query. This means the operation usually returns fewer users than specified in `maxResults`. To get all the users who match the structured query, use [Get all users](#api-rest-api-3-users-search-ge[...]
      operationId: atlassianFinduserkeysbyquery
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      summary: Atlassian Find User Keys By Query
      tags:
      - User Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:comment:jira
        - read:issue:jira
        - read:issue.vote:jira
        - read:issue.watcher:jira
        - read:project:jira
        - read:user.property:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/user/viewissue/search:
    get:
      deprecated: false
      description: Returns a list of users who fulfill these criteria:<br><br> *  their user attributes match a search string.<br> *  they have permission to browse issues.<br><br>Use this resource to find users who can browse:<br><br> *  an issue, by providing the `issueKey`.<br> *  any issue in a project, by providing the `projectKey`.<br><br>This operation takes the users in the range defined by `startAt` and `maxResults`, up to the thousandth user, and then returns only the users from that r[...]
      operationId: atlassianFinduserswithbrowsepermission
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      - {}
      summary: Atlassian Find Users With Browse Permission
      tags:
      - User Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue:jira
        - read:project:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.