openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Search API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Search
paths:
  /rest/api/3/issue/picker:
    get:
      deprecated: false
      description: Returns lists of issues matching a query string. Use this resource to provide auto-completion suggestions when the user is looking for an issue using a word or string.<br><br>This operation returns two lists:<br><br> *  `History Search` which includes issues from the user's history of created, edited, or viewed issues that contain the string in the `query` parameter.<br> *  `Current Search` which includes issues that match the JQL expression in `currentJQL` and contain the str[...]
      operationId: atlassianGetissuepickerresource
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Issue Picker Suggestions
      tags:
      - Issue Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-details:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/jql/match:
    post:
      deprecated: false
      description: Checks whether one or more issues would be returned by one or more JQL queries.<br><br>**[Permissions](#permissions) required:** None, however, issues are only matched against JQL queries where the user has:<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
      operationId: atlassianMatchissues
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Check Issues Against Jql
      tags:
      - Issue Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-details:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/search/id:
    post:
      deprecated: false
      description: Searches for IDs of issues using [JQL](https://confluence.atlassian.com/x/egORLQ).<br><br>Use the [Search](#api-rest-api-3-search-post) endpoint if you need to fetch more than just issue IDs. The Search endpoint returns more information, but may take much longer to respond to requests. This is because it uses a different mechanism for ordering results than this endpoint and doesn't provide the total number of results for your query.<br><br>This operation can be accessed anonym[...]
      operationId: atlassianSearchforissuesids
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Search Issue Ids Using Jql
      tags:
      - Issue Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-details:jira
        - read:field.default-value:jira
        - read:field.option:jira
        - read:field:jira
        - read:group:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: READ
  /rest/api/3/search:
    get:
      deprecated: false
      description: Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ).<br><br>If the JQL query expression is too large to be encoded as a query parameter, use the [POST](#api-rest-api-3-search-post) version of this resource.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** Issues are included in the response where the user has:<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) fo[...]
      operationId: atlassianSearchforissuesusingjql
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Search For Issues Using Jql Get
      tags:
      - Issue Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-details:jira
        - read:audit-log:jira
        - read:avatar:jira
        - read:field-configuration:jira
        - read:issue-meta:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Searches for issues using [JQL](https://confluence.atlassian.com/x/egORLQ).<br><br>There is a [GET](#api-rest-api-3-search-get) version of this resource that can be used for smaller JQL query expressions.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** Issues are included in the response where the user has:<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing [...]
      operationId: atlassianSearchforissuesusingjqlpost
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Search For Issues Using Jql Post
      tags:
      - Issue Search
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-details:jira
        - read:field.default-value:jira
        - read:field.option:jira
        - read:field:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.