openapi: 3.1.0
info:
  title: Atlassian Admin Account Filters API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Filters
paths:
  /rest/api/3/filter/favourite:
    get:
      deprecated: false
      description: Returns the visible favorite filters of the user.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** A favorite filter is only visible to the user where the filter is:<br><br> *  owned by the user.<br> *  shared with a group that the user is a member of.<br> *  shared with a private project that the user has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.<br> *  shared with a public project[...]
      operationId: atlassianGetfavouritefilters
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Favorite Filters
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:filter:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - read:jql:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/filter/my:
    get:
      deprecated: false
      description: Returns the filters owned by the user. If `includeFavourites` is `true`, the user's visible favorite filters are also returned.<br><br>**[Permissions](#permissions) required:** Permission to access Jira, however, a favorite filters is only visible to the user where the filter is:<br><br> *  owned by the user.<br> *  shared with a group that the user is a member of.<br> *  shared with a private project that the user has *Browse projects* [project permission](https://confluence.[...]
      operationId: atlassianGetmyfilters
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get My Filters
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:filter:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - read:jql:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/filter/search:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of filters. Use this operation to get:<br><br> *  specific filters, by defining `id` only.<br> *  filters that match all of the specified attributes. For example, all filters for a user with a particular word in their name. When multiple attributes are specified only filters matching all attributes are returned.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None, however, only the fol[...]
      operationId: atlassianGetfilterspaginated
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Search For Filters
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:filter:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - read:jql:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/filter/{id}:
    delete:
      deprecated: false
      description: Delete a filter.<br><br>**[Permissions](#permissions) required:** Permission to access Jira, however filters can only be deleted by the creator of the filter or a user with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeletefilter
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Delete Filter
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:filter:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns a filter.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None, however, the filter is only returned where it is:<br><br> *  owned by the user.<br> *  shared with a group that the user is a member of.<br> *  shared with a private project that the user has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.<br> *  shared with a public project.<br> *  shared with the public.
      operationId: atlassianGetfilter
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Filter
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:filter:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - read:jql:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Updates a filter. Use this operation to update a filter's name, description, JQL, or sharing.<br><br>**[Permissions](#permissions) required:** Permission to access Jira, however the user must own the filter.
      operationId: atlassianUpdatefilter
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Update Filter
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:filter:jira
        - read:filter:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - read:jql:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/filter/{id}/columns:
    delete:
      deprecated: false
      description: Reset the user's column configuration for the filter to the default.<br><br>**[Permissions](#permissions) required:** Permission to access Jira, however, columns are only reset for:<br><br> *  filters owned by the user.<br> *  filters shared with a group that the user is a member of.<br> *  filters shared with a private project that the user has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.<br> *  filters shared with a public project.<b[...]
      operationId: atlassianResetcolumns
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Reset Columns
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - delete:filter.column:jira
        state: Beta
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns the columns configured for a filter. The column configuration is used when the filter's results are viewed in *List View* with the *Columns* set to *Filter*.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None, however, column details are only returned for:<br><br> *  filters owned by the user.<br> *  filters shared with a group that the user is a member of.<br> *  filters shared with a private project that the user [...]
      operationId: atlassianGetcolumns
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Columns
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:filter.column:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Sets the columns for a filter. Only navigable fields can be set as columns. Use [Get fields](#api-rest-api-3-field-get) to get the list fields in Jira. A navigable field has `navigable` set to `true`.<br><br>The parameters for this resource are expressed as HTML form data. For example, in curl:<br><br>`curl -X PUT -d columns=summary -d columns=description https://your-domain.atlassian.net/rest/api/3/filter/10000/columns`<br><br>**[Permissions](#permissions) required:** Permiss[...]
      operationId: atlassianSetcolumns
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Set Columns
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:filter.column:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/filter/{id}/favourite:
    delete:
      deprecated: false
      description: Removes a filter as a favorite for the user. Note that this operation only removes filters visible to the user from the user's favorites list. For example, if the user favorites a public filter that is subsequently made private (and is therefore no longer visible on their favorites list) they cannot remove it from their favorites list.<br><br>**[Permissions](#permissions) required:** Permission to access Jira.
      operationId: atlassianDeletefavouriteforfilter
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Remove Filter As Favorite
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:filter:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:filter:jira
        - read:group:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-role:jira
        - read:project-version:jira
        - read:project.component:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    put:
      deprecated: false
      description: Add a filter as a favorite for the user.<br><br>**[Permissions](#permissions) required:** Permission to access Jira, however, the user can only favorite:<br><br> *  filters owned by the user.<br> *  filters shared with a group that the user is a member of.<br> *  filters shared with a private project that the user has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.<br> *  filters shared with a public project.<br> *  filters shared with th[...]
      operationId: atlassianSetfavouriteforfilter
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Add Filter As Favorite
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:filter:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - write:filter:jira
        - read:jql:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/filter/{id}/owner:
    put:
      deprecated: false
      description: Changes the owner of the filter.<br><br>**[Permissions](#permissions) required:** Permission to access Jira. However, the user must own the filter or have the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianChangefilterowner
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Change Filter Owner
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:filter:jira
        - write:filter:jira
        state: Beta
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      x-experimental: true
      x-atlassian-connect-scope: WRITE
  /rest/api/3/filter:
    post:
      deprecated: false
      description: Creates a filter. The filter is shared according to the [default share scope](#api-rest-api-3-filter-post). The filter is not selected as a favorite.<br><br>**[Permissions](#permissions) required:** Permission to access Jira.
      operationId: atlassianCreatefilter
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Create Filter
      tags:
      - Filters
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:filter:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - write:filter:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-version:jira
        - read:project.component:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.