openapi: 3.1.0
info:
  title: Atlassian Admin Account Dashboards API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Dashboards
paths:
  /rest/api/3/dashboard/bulk/edit:
    put:
      deprecated: false
      description: Bulk edit dashboards. Maximum number of dashboards to be edited at the same time is 100.<br><br>**[Permissions](#permissions) required:** None<br><br>The dashboards to be updated must be owned by the user, or the user must be an administrator.
      operationId: atlassianBulkeditdashboards
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      summary: Atlassian Bulk Edit Dashboards
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - write:dashboard:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-version:jira
        - read:project.component:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: WRITE
  /rest/api/3/dashboard/gadgets:
    get:
      deprecated: false
      description: Gets a list of all available gadgets that can be added to all dashboards.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianGetallavailabledashboardgadgets
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Get Available Gadgets
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: READ
  /rest/api/3/dashboard/search:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of dashboards. This operation is similar to [Get dashboards](#api-rest-api-3-dashboard-get) except that the results can be refined to include dashboards that have specific attributes. For example, dashboards with a particular name. When multiple attributes are specified only filters matching all attributes are returned.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** The following dashb[...]
      operationId: atlassianGetdashboardspaginated
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Search For Dashboards
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-version:jira
        - read:project.component:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/dashboard/{dashboardId}/gadget:
    get:
      deprecated: false
      description: Returns a list of dashboard gadgets on a dashboard.<br><br>This operation returns:<br><br> *  Gadgets from a list of IDs, when `id` is set.<br> *  Gadgets with a module key, when `moduleKey` is set.<br> *  Gadgets from a list of URIs, when `uri` is set.<br> *  All gadgets, when no other parameters are set.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianGetallgadgets
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Gadgets
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Adds a gadget to a dashboard.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianAddgadget
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
        - read:jira-work
      summary: Atlassian Add Gadget To Dashboard
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:dashboard:jira
        - read:dashboard:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: WRITE
  /rest/api/3/dashboard/{dashboardId}/gadget/{gadgetId}:
    delete:
      deprecated: false
      description: Removes a dashboard gadget from a dashboard.<br><br>When a gadget is removed from a dashboard, other gadgets in the same column are moved up to fill the emptied position.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianRemovegadget
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      summary: Atlassian Remove Gadget From Dashboard
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:dashboard:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: DELETE
    put:
      deprecated: false
      description: Changes the title, position, and color of the gadget on a dashboard.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianUpdategadget
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      summary: Atlassian Update Gadget On Dashboard
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:dashboard:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: WRITE
  /rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties:
    get:
      deprecated: false
      description: Returns the keys of all properties for a dashboard item.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** The user must be the owner of the dashboard or have the dashboard shared with them. Note, users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) are considered owners of the System dashboard. The System dashboard is considered to be shared with all other users, and is accessible to [...]
      operationId: atlassianGetdashboarditempropertykeys
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Dashboard Item Property Keys
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard.property:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}:
    delete:
      deprecated: false
      description: Deletes a dashboard item property.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** The user must be the owner of the dashboard. Note, users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) are considered owners of the System dashboard.
      operationId: atlassianDeletedashboarditemproperty
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Delete Dashboard Item Property
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:dashboard.property:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns the key and value of a dashboard item property.<br><br>A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).<br><br>When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires[...]
      operationId: atlassianGetdashboarditemproperty
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Dashboard Item Property
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard.property:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Sets the value of a dashboard item property. Use this resource in apps to store custom data against a dashboard item.<br><br>A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).<br><br>When an app creates a dashboard item it registers a[...]
      operationId: atlassianSetdashboarditemproperty
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Set Dashboard Item Property
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:dashboard.property:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/dashboard/{id}:
    delete:
      deprecated: false
      description: Deletes a dashboard.<br><br>**[Permissions](#permissions) required:** None<br><br>The dashboard to be deleted must be owned by the user.
      operationId: atlassianDeletedashboard
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Delete Dashboard
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:dashboard:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns a dashboard.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None.<br><br>However, to get a dashboard, the dashboard must be shared with the user or the user must own it. Note, users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) are considered owners of the System dashboard. The System dashboard is considered to be shared with all other users.
      operationId: atlassianGetdashboard
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Dashboard
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-version:jira
        - read:project.component:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Updates a dashboard, replacing all the dashboard details with those provided.<br><br>**[Permissions](#permissions) required:** None<br><br>The dashboard to be updated must be owned by the user.
      operationId: atlassianUpdatedashboard
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Update Dashboard
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - write:dashboard:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-version:jira
        - read:project.component:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: WRITE
  /rest/api/3/dashboard/{id}/copy:
    post:
      deprecated: false
      description: Copies a dashboard. Any values provided in the `dashboard` parameter replace those in the copied dashboard.<br><br>**[Permissions](#permissions) required:** None<br><br>The dashboard to be copied must be owned by or shared with the user.
      operationId: atlassianCopydashboard
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Copy Dashboard
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - write:dashboard:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-version:jira
        - read:project.component:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: WRITE
  /rest/api/3/dashboard:
    get:
      deprecated: false
      description: Returns a list of dashboards owned by or shared with the user. The list may be filtered to include only favorite or owned dashboards.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianGetalldashboards
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get All Dashboards
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-version:jira
        - read:project.component:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Creates a dashboard.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianCreatedashboard
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Create Dashboard
      tags:
      - Dashboards
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:dashboard:jira
        - read:group:jira
        - read:project:jira
        - read:project-role:jira
        - read:user:jira
        - write:dashboard:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:issue-type-hierarchy:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project-version:jira
        - read:project.component:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: WRITE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.