openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Type Schemes API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Type Schemes
paths:
  /rest/api/3/issuetypescheme/mapping:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of issue type scheme items.<br><br>Only issue type scheme items used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuetypeschemesmapping
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Type Scheme Items
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescheme/project:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of issue type schemes and, for each issue type scheme, a list of the projects that use it.<br><br>Only issue type schemes used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuetypeschemeforprojects
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Type Schemes For Projects
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Assigns an issue type scheme to a project.<br><br>If any issues in the project are assigned issue types not present in the new scheme, the operation will fail. To complete the assignment those issues must be updated to use issue types in the new scheme.<br><br>Issue type schemes can only be assigned to classic projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAssignissuetypeschemetoproject
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Assign Issue Type Scheme To Project
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-scheme:jira
        - write:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescheme/{issueTypeSchemeId}:
    delete:
      deprecated: false
      description: Deletes an issue type scheme.<br><br>Only issue type schemes used in classic projects can be deleted.<br><br>Any projects assigned to the scheme are reassigned to the default issue type scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteissuetypescheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Issue Type Scheme
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:issue-type-scheme:jira
        - write:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates an issue type scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdateissuetypescheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Issue Type Scheme
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescheme/{issueTypeSchemeId}/issuetype:
    put:
      deprecated: false
      description: Adds issue types to an issue type scheme.<br><br>The added issue types are appended to the issue types list.<br><br>If any of the issue types exist in the issue type scheme, the operation fails and no issue types are added.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAddissuetypestoissuetypescheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Add Issue Types To Issue Type Scheme
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescheme/{issueTypeSchemeId}/issuetype/move:
    put:
      deprecated: false
      description: Changes the order of issue types in an issue type scheme.<br><br>The request body parameters must meet the following requirements:<br><br> *  all of the issue types must belong to the issue type scheme.<br> *  either `after` or `position` must be provided.<br> *  the issue type in `after` must not be in the issue type list.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianReorderissuetypesinissuetypescheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Change Order Of Issue Types
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescheme/{issueTypeSchemeId}/issuetype/{issueTypeId}:
    delete:
      deprecated: false
      description: Removes an issue type from an issue type scheme.<br><br>This operation cannot remove:<br><br> *  any issue type used by issues.<br> *  any issue types from the default issue type scheme.<br> *  the last standard issue type from an issue type scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianRemoveissuetypefromissuetypescheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Remove Issue Type From Issue Type Scheme
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescheme:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of issue type schemes.<br><br>Only issue type schemes used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetallissuetypeschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get All Issue Type Schemes
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    post:
      deprecated: false
      description: Creates an issue type scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreateissuetypescheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Issue Type Scheme
      tags:
      - Issue Type Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.