openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Type Screen Schemes API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Type Screen Schemes
paths:
  /rest/api/3/issuetypescreenscheme/mapping:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of issue type screen scheme items.<br><br>Only issue type screen schemes used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuetypescreenschememappings
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Type Screen Scheme Items
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescreenscheme/project:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of issue type screen schemes and, for each issue type screen scheme, a list of the projects that use it.<br><br>Only issue type screen schemes used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuetypescreenschemeprojectassociations
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Type Screen Schemes For Projects
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Assigns an issue type screen scheme to a project.<br><br>Issue type screen schemes can only be assigned to classic projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAssignissuetypescreenschemetoproject
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Assign Issue Type Screen Scheme To Project
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-screen-scheme:jira
        - write:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}:
    delete:
      deprecated: false
      description: Deletes an issue type screen scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteissuetypescreenscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Issue Type Screen Scheme
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates an issue type screen scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdateissuetypescreenscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Issue Type Screen Scheme
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping:
    put:
      deprecated: false
      description: Appends issue type to screen scheme mappings to an issue type screen scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAppendmappingsforissuetypescreenscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Append Mappings To Issue Type Screen Scheme
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping/default:
    put:
      deprecated: false
      description: Updates the default screen scheme of an issue type screen scheme. The default screen scheme is used for all unmapped issue types.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatedefaultscreenscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Issue Type Screen Scheme Default Screen Scheme
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}/mapping/remove:
    post:
      deprecated: false
      description: Removes issue type to screen scheme mappings from an issue type screen scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianRemovemappingsfromissuetypescreenscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Remove Mappings From Issue Type Screen Scheme
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescreenscheme/{issueTypeScreenSchemeId}/project:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of projects associated with an issue type screen scheme.<br><br>Only company-managed projects associated with an issue type screen scheme are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetprojectsforissuetypescreenscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Type Screen Scheme Projects
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:project:jira
        - read:avatar:jira
        - read:project-category:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetypescreenscheme:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of issue type screen schemes.<br><br>Only issue type screen schemes used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuetypescreenschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Type Screen Schemes
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    post:
      deprecated: false
      description: Creates an issue type screen scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreateissuetypescreenscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Issue Type Screen Scheme
      tags:
      - Issue Type Screen Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type-screen-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.