openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Custom Field Contexts API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Custom Field Contexts
paths:
  /rest/api/3/field/{fieldId}/context:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of [ contexts](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html) for a custom field. Contexts can be returned as follows:<br><br> *  With no other parameters set, all contexts.<br> *  By defining `id` only, all contexts from the list of IDs.<br> *  By defining `isAnyIssueType`, limit the list of contexts returned to either those that apply to all issue types (true) or those that apply to only [...]
      operationId: atlassianGetcontextsforfield
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Custom Field Contexts
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        - read:custom-field-contextual-configuration:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Creates a custom field context.<br><br>If `projectIds` is empty, a global context is created. A global context is one that applies to all project. If `issueTypeIds` is empty, the context applies to all issue types.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreatecustomfieldcontext
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Custom Field Context
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        - write:field:jira
        - read:custom-field-contextual-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{fieldId}/context/defaultValue:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of defaults for a custom field. The results can be filtered by `contextId`, otherwise all values are returned. If no defaults are set for a context, nothing is returned.  <br>The returned object depends on type of the custom field:<br><br> *  `CustomFieldContextDefaultValueDate` (type `datepicker`) for date fields.<br> *  `CustomFieldContextDefaultValueDateTime` (type `datetimepicker`) for date-time fields.<br> *  `CustomFieldContextDefa[...]
      operationId: atlassianGetdefaultvalues
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Custom Field Contexts Default Values
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field.default-value:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Sets default for contexts of a custom field. Default are defined using these objects:<br><br> *  `CustomFieldContextDefaultValueDate` (type `datepicker`) for date fields.<br> *  `CustomFieldContextDefaultValueDateTime` (type `datetimepicker`) for date-time fields.<br> *  `CustomFieldContextDefaultValueSingleOption` (type `option.single`) for single choice select lists and radio buttons.<br> *  `CustomFieldContextDefaultValueMultipleOption` (type `option.multiple`) for multiple[...]
      operationId: atlassianSetdefaultvalues
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Set Custom Field Contexts Default Values
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field.default-value:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{fieldId}/context/issuetypemapping:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of context to issue type mappings for a custom field. Mappings are returned for all contexts or a list of contexts. Mappings are ordered first by context ID and then by issue type ID.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuetypemappingsforcontexts
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Types For Custom Field Context
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/field/{fieldId}/context/mapping:
    post:
      deprecated: false
      description: Returns a [paginated](#pagination) list of project and issue type mappings and, for each mapping, the ID of a [custom field context](https://confluence.atlassian.com/x/k44fOw) that applies to the project and issue type.<br><br>If there is no custom field context assigned to the project then, if present, the custom field context that applies to all projects is returned if it also applies to the issue type or all issue types. If a custom field context is not found, the returned [...]
      operationId: atlassianGetcustomfieldcontextsforprojectsandissuetypes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Custom Field Contexts For Projects And Issue Types
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{fieldId}/context/projectmapping:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of context to project mappings for a custom field. The result can be filtered by `contextId`. Otherwise, all mappings are returned. Invalid IDs are ignored.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetprojectcontextmapping
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Project Mappings For Custom Field Context
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/field/{fieldId}/context/{contextId}:
    delete:
      deprecated: false
      description: Deletes a [ custom field context](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html).<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeletecustomfieldcontext
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Custom Field Context
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates a [ custom field context](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html).<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatecustomfieldcontext
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Custom Field Context
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{fieldId}/context/{contextId}/issuetype:
    put:
      deprecated: false
      description: Adds issue types to a custom field context, appending the issue types to the issue types list.<br><br>A custom field context without any issue types applies to all issue types. Adding issue types to such a custom field context would result in it applying to only the listed issue types.<br><br>If any of the issue types exists in the custom field context, the operation fails and no issue types are added.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global [...]
      operationId: atlassianAddissuetypestocontext
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Add Issue Types To Context
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{fieldId}/context/{contextId}/issuetype/remove:
    post:
      deprecated: false
      description: Removes issue types from a custom field context.<br><br>A custom field context without any issue types applies to all issue types.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianRemoveissuetypesfromcontext
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Remove Issue Types From Context
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{fieldId}/context/{contextId}/project:
    put:
      deprecated: false
      description: Assigns a custom field context to projects.<br><br>If any project in the request is assigned to any context of the custom field, the operation fails.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAssignprojectstocustomfieldcontext
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Assign Custom Field Context To Projects
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{fieldId}/context/{contextId}/project/remove:
    post:
      deprecated: false
      description: Removes a custom field context from projects.<br><br>A custom field context without any projects applies to all projects. Removing all projects from a custom field context would result in it applying to all projects.<br><br>If any project in the request is not assigned to the context, or the operation would result in two global contexts for the field, the operation fails.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.[...]
      operationId: atlassianRemovecustomfieldcontextfromprojects
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Remove Custom Field Context From Projects
      tags:
      - Issue Custom Field Contexts
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.