openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Properties API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Properties
paths:
  /rest/api/3/issue/properties:
    post:
      deprecated: false
      description: Sets or updates a list of entity property values on issues. A list of up to 10 entity properties can be specified along with up to 10,000 issues on which to set or update that list of entity properties.<br><br>The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON. The maximum length of single issue property value is 32768 characters. This operation can be accessed anonymously.<br><br>This operation is:<br><br> *  transactional, eit[...]
      operationId: atlassianBulksetissuespropertieslist
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      summary: Atlassian Bulk Set Issues Properties By List
      tags:
      - Issue Properties
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue.property:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/issue/properties/multi:
    post:
      deprecated: false
      description: Sets or updates entity property values on issues. Up to 10 entity properties can be specified for each issue and up to 100 issues included in the request.<br><br>The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON.<br><br>This operation is:<br><br> *  [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updat[...]
      operationId: atlassianBulksetissuepropertiesbyissue
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      summary: Atlassian Bulk Set Issue Properties By Issue
      tags:
      - Issue Properties
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue.property:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/issue/properties/{propertyKey}:
    delete:
      deprecated: false
      description: 'Deletes a property value from multiple issues. The issues to be updated can be specified by filter criteria.<br><br>The criteria the filter used to identify eligible issues are:<br><br> *  `entityIds` Only issues from this list are eligible.<br> *  `currentValue` Only issues with the property set to this value are eligible.<br><br>If both criteria is specified, they are joined with the logical *AND*: only issues that satisfy both criteria are considered eligible.<br><br>If no[...]'
      operationId: atlassianBulkdeleteissueproperty
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      summary: Atlassian Bulk Delete Issue Property
      tags:
      - Issue Properties
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:issue.property:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    put:
      deprecated: false
      description: 'Sets a property value on multiple issues.<br><br>The value set can be a constant or determined by a [Jira expression](https://developer.atlassian.com/cloud/jira/platform/jira-expressions/). Expressions must be computable with constant complexity when applied to a set of issues. Expressions must also comply with the [restrictions](https://developer.atlassian.com/cloud/jira/platform/jira-expressions/#restrictions) that apply to all Jira expressions.<br><br>The issues to be upda[...]'
      operationId: atlassianBulksetissueproperty
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      summary: Atlassian Bulk Set Issue Property
      tags:
      - Issue Properties
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:jira-expressions:jira
        - write:issue.property:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/issue/{issueIdOrKey}/properties:
    get:
      deprecated: false
      description: Returns the URLs and keys of an issue's properties.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** Property details are only returned where the user has:<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.<br> *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
      operationId: atlassianGetissuepropertykeys
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Issue Property Keys
      tags:
      - Issue Properties
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue.property:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/issue/{issueIdOrKey}/properties/{propertyKey}:
    delete:
      deprecated: false
      description: Deletes an issue's property.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* and *Edit issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.<br> *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
      operationId: atlassianDeleteissueproperty
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Delete Issue Property
      tags:
      - Issue Properties
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:issue.property:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns the key and value of an issue's property.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.<br> *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
      operationId: atlassianGetissueproperty
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Issue Property
      tags:
      - Issue Properties
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue.property:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Sets the value of an issue's property. Use this resource to store custom data against an issue.<br><br>The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* and *Edit issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project cont[...]
      operationId: atlassianSetissueproperty
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Set Issue Property
      tags:
      - Issue Properties
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue.property:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.