openapi: 3.1.0
info:
  title: Atlassian Admin Account Workflow Schemes API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Workflow Schemes
paths:
  /rest/api/3/workflowscheme/read:
    post:
      deprecated: false
      description: Returns a list of workflow schemes by providing workflow scheme IDs or project IDs.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* global permission to access all, including project-scoped, workflow schemes<br> *  *Administer projects* project permissions to access project-scoped workflow schemes
      operationId: atlassianReadworkflowschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Bulk Get Workflow Schemes
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/update:
    post:
      deprecated: false
      description: Updates company-managed and team-managed project workflow schemes. This API doesn't have a concept of draft, so any changes made to a workflow scheme are immediately available. When changing the available statuses for issue types, an [asynchronous task](#async) migrates the issues as defined in the provided mappings.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* project permission to update all, including global-scoped, workflow schemes.<br> *  [...]
      operationId: atlassianUpdateschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/update/mappings:
    post:
      deprecated: false
      description: Gets the required status mappings for the desired changes to a workflow scheme. The results are provided per issue type and workflow. When updating a workflow scheme, status mappings can be provided per issue type, per workflow, or both.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* permission to update all, including global-scoped, workflow schemes.<br> *  *Administer projects* project permission to update project-scoped workflow schemes.
      operationId: atlassianUpdateworkflowschememappings
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Required Status Mappings For Workflow Scheme Update
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}:
    delete:
      deprecated: false
      description: Deletes a workflow scheme. Note that a workflow scheme cannot be deleted if it is active (that is, being used by at least one project).<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteworkflowscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:workflow-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns a workflow scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetworkflowscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates a company-manged project workflow scheme, including the name, default workflow, issue type to project mappings, and more. If the workflow scheme is active (that is, being used by at least one project), then a draft workflow scheme is created or updated instead, provided that `updateDraftIfNeeded` is set to `true`.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdateworkflowscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Classic Update Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - write:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}/default:
    delete:
      deprecated: false
      description: Resets the default workflow for a workflow scheme. That is, the default workflow is set to Jira's system workflow (the *jira* workflow).<br><br>Note that active workflow schemes cannot be edited. If the workflow scheme is active, set `updateDraftIfNeeded` to `true` and a draft workflow scheme is created or updated with the default workflow reset. The draft workflow scheme can be published in Jira.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permi[...]
      operationId: atlassianDeletedefaultworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Default Workflow
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - write:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns the default workflow for a workflow scheme. The default workflow is the workflow that is assigned any issue types that have not been mapped to any other workflow. The default workflow has *All Unassigned Issue Types* listed in its issue types for the workflow scheme in Jira.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetdefaultworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Default Workflow
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - read:workflow:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Sets the default workflow for a workflow scheme.<br><br>Note that active workflow schemes cannot be edited. If the workflow scheme is active, set `updateDraftIfNeeded` to `true` in the request object and a draft workflow scheme is created or updated with the new default workflow. The draft workflow scheme can be published in Jira.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatedefaultworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Default Workflow
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - write:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}/issuetype/{issueType}:
    delete:
      deprecated: false
      description: Deletes the issue type-workflow mapping for an issue type in a workflow scheme.<br><br>Note that active workflow schemes cannot be edited. If the workflow scheme is active, set `updateDraftIfNeeded` to `true` and a draft workflow scheme is created or updated with the issue type-workflow mapping deleted. The draft workflow scheme can be published in Jira.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4[...]
      operationId: atlassianDeleteworkflowschemeissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Workflow For Issue Type In Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns the issue type-workflow mapping for an issue type in a workflow scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetworkflowschemeissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Workflow For Issue Type In Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:issue-type:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Sets the workflow for an issue type in a workflow scheme.<br><br>Note that active workflow schemes cannot be edited. If the workflow scheme is active, set `updateDraftIfNeeded` to `true` in the request body and a draft workflow scheme is created or updated with the new issue type-workflow mapping. The draft workflow scheme can be published in Jira.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianSetworkflowschemeissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Set Workflow For Issue Type In Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme/{id}/workflow:
    delete:
      deprecated: false
      description: Deletes the workflow-issue type mapping for a workflow in a workflow scheme.<br><br>Note that active workflow schemes cannot be edited. If the workflow scheme is active, set `updateDraftIfNeeded` to `true` and a draft workflow scheme is created or updated with the workflow-issue type mapping deleted. The draft workflow scheme can be published in Jira.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKL[...]
      operationId: atlassianDeleteworkflowmapping
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Issue Types For Workflow In Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:workflow-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns the workflow-issue type mappings for a workflow scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Types For Workflows In Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:issue-type:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Sets the issue types for a workflow in a workflow scheme. The workflow can also be set as the default workflow for the workflow scheme. Unmapped issues types are mapped to the default workflow.<br><br>Note that active workflow schemes cannot be edited. If the workflow scheme is active, set `updateDraftIfNeeded` to `true` in the request body and a draft workflow scheme is created or updated with the new workflow-issue types mappings. The draft workflow scheme can be published i[...]
      operationId: atlassianUpdateworkflowmapping
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Set Issue Types For Workflow In Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        - read:workflow-scheme:jira
        - read:workflow:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflowscheme:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of all workflow schemes, not including draft workflow schemes.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetallworkflowschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get All Workflow Schemes
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    post:
      deprecated: false
      description: Creates a workflow scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreateworkflowscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Workflow Scheme
      tags:
      - Workflow Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow-scheme:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:user:jira
        - read:workflow-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.