openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Custom Field Options (Apps) API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Custom Field Options (Apps)
paths:
  /rest/api/3/field/{fieldKey}/option:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of all the options of a select list issue field. A select list issue field is a type of [issue field](https://developer.atlassian.com/cloud/jira/platform/modules/issue-field/) that enables a user to select a value from a list of options.<br><br>Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from t[...]
      operationId: atlassianGetallissuefieldoptions
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get All Issue Field Options
      tags:
      - Issue Custom Field Options (Apps)
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field.option:jira
        state: Beta
      x-atlassian-connect-scope: NONE
    post:
      deprecated: false
      description: Creates an option for a select list issue field.<br><br>Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.<br><br>Each field can have a maximum of 10000 options, and each option can have a maximum of 10000 scopes.<br><br>**[Permissions](#permissions) requ[...]
      operationId: atlassianCreateissuefieldoption
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Issue Field Option
      tags:
      - Issue Custom Field Options (Apps)
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field.option:jira
        state: Beta
      x-atlassian-connect-scope: NONE
  /rest/api/3/field/{fieldKey}/option/suggestions/edit:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of options for a select list issue field that can be viewed and selected by the user.<br><br>Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.<br><br>**[Permissions](#permissions) required:** Permission to access J[...]
      operationId: atlassianGetselectableissuefieldoptions
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Get Selectable Issue Field Options
      tags:
      - Issue Custom Field Options (Apps)
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field.option:jira
        state: Beta
      x-atlassian-connect-scope: NONE
  /rest/api/3/field/{fieldKey}/option/suggestions/search:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of options for a select list issue field that can be viewed by the user.<br><br>Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.<br><br>**[Permissions](#permissions) required:** Permission to access Jira.
      operationId: atlassianGetvisibleissuefieldoptions
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Get Visible Issue Field Options
      tags:
      - Issue Custom Field Options (Apps)
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field.option:jira
        state: Beta
      x-atlassian-connect-scope: NONE
  /rest/api/3/field/{fieldKey}/option/{optionId}:
    delete:
      deprecated: false
      description: Deletes an option from a select list issue field.<br><br>Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). Jira permissions[...]
      operationId: atlassianDeleteissuefieldoption
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Issue Field Option
      tags:
      - Issue Custom Field Options (Apps)
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:field.option:jira
        state: Beta
      x-atlassian-connect-scope: NONE
    get:
      deprecated: false
      description: Returns an option from a select list issue field.<br><br>Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). Jira permissions[...]
      operationId: atlassianGetissuefieldoption
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Field Option
      tags:
      - Issue Custom Field Options (Apps)
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field.option:jira
        state: Beta
      x-atlassian-connect-scope: NONE
    put:
      deprecated: false
      description: Updates or creates an option for a select list issue field. This operation requires that the option ID is provided when creating an option, therefore, the option ID needs to be specified as a path and body parameter. The option ID provided in the path and body must be identical.<br><br>Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from[...]
      operationId: atlassianUpdateissuefieldoption
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Issue Field Option
      tags:
      - Issue Custom Field Options (Apps)
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field.option:jira
        state: Beta
      x-atlassian-connect-scope: NONE
  /rest/api/3/field/{fieldKey}/option/{optionId}/issue:
    delete:
      deprecated: false
      description: Deselects an issue-field select-list option from all issues where it is selected. A different option can be selected to replace the deselected option. The update can also be limited to a smaller set of issues by using a JQL query.<br><br>Connect and Forge app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) can override the screen security configuration using `overrideScreenSecurity` and `overrideEditableFlag`.<br><br>This is an [asyn[...]
      operationId: atlassianReplaceissuefieldoption
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Replace Issue Field Option
      tags:
      - Issue Custom Field Options (Apps)
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field.option:jira
        - delete:field.option:jira
        state: Beta
      x-atlassian-connect-scope: NONE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.