openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Types API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Types
paths:
  /rest/api/3/issuetype/project:
    get:
      deprecated: false
      description: Returns issue types for a project.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) in the relevant project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuetypesforproject
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Issue Types For Project
      tags:
      - Issue Types
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type:jira
        - read:avatar:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: READ
  /rest/api/3/issuetype/{id}:
    delete:
      deprecated: false
      description: Deletes the issue type. If the issue type is in use, all uses are updated with the alternative issue type (`alternativeIssueTypeId`). A list of alternative issue types are obtained from the [Get alternative issue types](#api-rest-api-3-issuetype-id-alternatives-get) resource.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      - {}
      summary: Atlassian Delete Issue Type
      tags:
      - Issue Types
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:issue-type:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns an issue type.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) in a project the issue type is associated with or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Issue Type
      tags:
      - Issue Types
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type:jira
        - read:avatar:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Updates the issue type.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdateissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      - {}
      summary: Atlassian Update Issue Type
      tags:
      - Issue Types
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type:jira
        - read:avatar:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetype/{id}/alternatives:
    get:
      deprecated: false
      description: Returns a list of issue types that can be used to replace the issue type. The alternative issue types are those assigned to the same workflow scheme, field configuration scheme, and screen scheme.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianGetalternativeissuetypes
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Alternative Issue Types
      tags:
      - Issue Types
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/issuetype/{id}/avatar2:
    post:
      deprecated: false
      description: 'Loads an avatar for the issue type.<br><br>Specify the avatar''s local file location in the body of the request. Also, include the following headers:<br><br> *  `X-Atlassian-Token: no-check` To prevent XSRF protection blocking the request, for more information see [Special Headers](#special-request-headers).<br> *  `Content-Type: image/image type` Valid image types are JPEG, GIF, or PNG.<br><br>For example:  <br>`curl --request POST \ --user email@example.com: \ --header ''X-[...]'
      operationId: atlassianCreateissuetypeavatar
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      - {}
      summary: Atlassian Load Issue Type Avatar
      tags:
      - Issue Types
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:avatar:jira
        - write:issue-type:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuetype:
    get:
      deprecated: false
      description: Returns all issue types.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** Issue types are only returned as follows:<br><br> *  if the user has the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), all issue types are returned.<br> *  if the user has the *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for one or more projects, the issue types associated with the [...]
      operationId: atlassianGetissuealltypes
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get All Issue Types For User
      tags:
      - Issue Types
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-type:jira
        - read:avatar:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Creates an issue type and adds it to the default issue type scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreateissuetype
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      - {}
      summary: Atlassian Create Issue Type
      tags:
      - Issue Types
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-type:jira
        - read:avatar:jira
        - read:issue-type:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.