openapi: 3.1.0
info:
  title: Atlassian Admin Account Relation API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Relation
paths:
  /wiki/rest/api/relation/{relationName}/from/{sourceType}/{sourceKey}/to/{targetType}:
    get:
      tags:
      - Relation
      summary: Atlassian Find Target Entities Related to a Source Entity
      description: Returns all target entities that have a particular relationship to the<br>source entity. Note, relationships are one way.<br><br>For example, the following method finds all content that the current user<br>has an 'ignore' relationship with:<br>`GET /wiki/rest/api/relation/ignore/from/user/current/to/content`<br>Note, 'ignore' is an example custom relationship type.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to view both the targ[...]
      operationId: atlassianFindtargetfromsource
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:relation:confluence
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/relation/{relationName}/from/{sourceType}/{sourceKey}/to/{targetType}/{targetKey}:
    get:
      tags:
      - Relation
      summary: Atlassian Find Relationship From Source to Target
      description: Find whether a particular type of relationship exists from a source<br>entity to a target entity. Note, relationships are one way.<br><br>For example, you can use this method to find whether the current user has<br>selected a particular page as a favorite (i.e. 'save for later'):<br>`GET /wiki/rest/api/relation/favourite/from/user/current/to/content/123`<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to view both the target entity a[...]
      operationId: atlassianGetrelationship
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:relation:confluence
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      tags:
      - Relation
      summary: Atlassian Create Relationship
      description: Creates a relationship between two entities (user, space, content). The<br>'favourite' relationship is supported by default, but you can use this method<br>to create any type of relationship between two entities.<br><br>For example, the following method creates a 'sibling' relationship between<br>two pieces of content:<br>`GET /wiki/rest/api/relation/sibling/from/content/123/to/content/456`<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permis[...]
      operationId: atlassianCreaterelationship
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:relation:confluence
        - read:space:confluence
        - read:user:confluence
        - read:content:confluence
        - write:relation:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Relation
      summary: Atlassian Delete Relationship
      description: Deletes a relationship between two entities (user, space, content).<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to access the Confluence site ('Can use' global permission).<br>For favourite relationships, the current user can only delete their own<br>favourite relationships. A space administrator can delete favourite<br>relationships for any user.
      operationId: atlassianDeleterelationship
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:relation:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/relation/{relationName}/to/{targetType}/{targetKey}/from/{sourceType}:
    get:
      tags:
      - Relation
      summary: Atlassian Find Source Entities Related to a Target Entity
      description: Returns all target entities that have a particular relationship to the<br>source entity. Note, relationships are one way.<br><br>For example, the following method finds all users that have a 'collaborator'<br>relationship to a piece of content with an ID of '1234':<br>`GET /wiki/rest/api/relation/collaborator/to/content/1234/from/user`<br>Note, 'collaborator' is an example custom relationship type.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<b[...]
      operationId: atlassianFindsourcesfortarget
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:relation:confluence
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.