openapi: 3.1.0
info:
  title: Atlassian Admin Account Project Components API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Project Components
paths:
  /rest/api/3/component/{id}:
    delete:
      deprecated: false
      description: Deletes a component.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the component or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeletecomponent
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      - {}
      summary: Atlassian Delete Component
      tags:
      - Project Components
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:project.component:jira
        state: Beta
      x-atlassian-connect-scope: PROJECT_ADMIN
    get:
      deprecated: false
      description: Returns a component.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for project containing the component.
      operationId: atlassianGetcomponent
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Component
      tags:
      - Project Components
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:project:jira
        - read:project.component:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Updates a component. Any fields included in the request are overwritten. If `leadAccountId` is an empty string ("") the component lead is removed.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the component or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatecomponent
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      - {}
      summary: Atlassian Update Component
      tags:
      - Project Components
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - read:project:jira
        - read:user:jira
        - write:project.component:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:project.component:jira
        state: Beta
      x-atlassian-connect-scope: PROJECT_ADMIN
  /rest/api/3/component/{id}/relatedIssueCounts:
    get:
      deprecated: false
      description: 'Returns the counts of issues assigned to the component.<br><br>This operation can be accessed anonymously.<br><br>**Deprecation notice:** The required OAuth 2.0 scopes will be updated on June 15, 2024.<br><br> *  **Classic**: `read:jira-work`<br> *  **Granular**: `read:field:jira`, `read:project.component:jira`<br><br>**[Permissions](#permissions) required:** None.'
      operationId: atlassianGetcomponentrelatedissues
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Component Issues Count
      tags:
      - Project Components
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes: []
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/project/{projectIdOrKey}/component:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of all components in a project. See the [Get project components](#api-rest-api-3-project-projectIdOrKey-components-get) resource if you want to get a full list of versions without pagination.<br><br>If your project uses Compass components, this API will return a list of Compass components that are linked to issues in that project.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Browse [...]
      operationId: atlassianGetprojectcomponentspaginated
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Project Components Paginated
      tags:
      - Project Components
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:project:jira
        - read:project.component:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/project/{projectIdOrKey}/components:
    get:
      deprecated: false
      description: Returns all components in a project. See the [Get project components paginated](#api-rest-api-3-project-projectIdOrKey-component-get) resource if you want to get a full list of components with pagination.<br><br>If your project uses Compass components, this API will return a paginated list of Compass components that are linked to issues in that project.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Browse Projects* [projec[...]
      operationId: atlassianGetprojectcomponents
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Project Components
      tags:
      - Project Components
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:project:jira
        - read:project.component:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/component:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of all components in a project, including global (Compass) components when applicable.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
      operationId: atlassianFindcomponentsforprojects
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Find Components For Projects
      tags:
      - Project Components
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:project:jira
        - read:project.component:jira
        - read:user:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Creates a component. Use components to provide containers for issues within a project. Use components to provide containers for issues within a project.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project in which the component is created or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreatecomponent
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      - {}
      summary: Atlassian Create Component
      tags:
      - Project Components
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - read:project:jira
        - read:user:jira
        - write:project.component:jira
        - read:application-role:jira
        - read:avatar:jira
        - read:group:jira
        - read:project.component:jira
        state: Beta
      x-atlassian-connect-scope: PROJECT_ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.