openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Remote Links API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Remote Links
paths:
  /rest/api/3/issue/{issueIdOrKey}/remotelink:
    delete:
      deprecated: false
      description: Deletes the remote issue link from the issue using the link's global ID. Where the global ID includes reserved URL characters these must be escaped in the request. For example, pass `system=http://www.mycompany.com/support&id=1` as `system%3Dhttp%3A%2F%2Fwww.mycompany.com%2Fsupport%26id%3D1`.<br><br>This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissio[...]
      operationId: atlassianDeleteremoteissuelinkbyglobalid
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Delete Remote Issue Link By Global Id
      tags:
      - Issue Remote Links
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:issue.remote-link:jira
        - write:issue:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns the remote issue links for an issue. When a remote issue link global ID is provided the record with that global ID is returned, otherwise all remote issue links are returned. Where a global ID includes reserved URL characters these must be escaped in the request. For example, pass `system=http://www.mycompany.com/support&id=1` as `system%3Dhttp%3A%2F%2Fwww.mycompany.com%2Fsupport%26id%3D1`.<br><br>This operation requires [issue linking to be active](https://confluence.[...]
      operationId: atlassianGetremoteissuelinks
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Remote Issue Links
      tags:
      - Issue Remote Links
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue.remote-link:jira
        - read:status:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Creates or updates a remote issue link for an issue.<br><br>If a `globalId` is provided and a remote issue link with that global ID is found it is updated. Any fields without values in the request are set to null. Otherwise, the remote issue link is created.<br><br>This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse [...]
      operationId: atlassianCreateorupdateremoteissuelink
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Create Or Update Remote Issue Link
      tags:
      - Issue Remote Links
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue:jira
        - write:issue.remote-link:jira
        - read:issue.remote-link:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/issue/{issueIdOrKey}/remotelink/{linkId}:
    delete:
      deprecated: false
      description: Deletes a remote issue link from an issue.<br><br>This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects*, *Edit issues*, and *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-level security](https://confluence.atlassian.com/x/J4[...]
      operationId: atlassianDeleteremoteissuelinkbyid
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Delete Remote Issue Link By Id
      tags:
      - Issue Remote Links
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:issue.remote-link:jira
        - write:issue:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns a remote issue link for an issue.<br><br>This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level se[...]
      operationId: atlassianGetremoteissuelinkbyid
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Remote Issue Link By Id
      tags:
      - Issue Remote Links
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue.remote-link:jira
        - read:status:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: 'Updates a remote issue link for an issue.<br><br>Note: Fields without values in the request are set to null.<br><br>This operation requires [issue linking to be active](https://confluence.atlassian.com/x/yoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* and *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-le[...]'
      operationId: atlassianUpdateremoteissuelink
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Update Remote Issue Link By Id
      tags:
      - Issue Remote Links
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue:jira
        - write:issue.remote-link:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.