openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Tracker API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Tracker
paths:
  /repositories/{workspace}/{repo_slug}/components:
    get:
      tags:
      - Issue Tracker
      description: Returns the components that have been defined in the issue tracker.<br><br>This resource is only available on repositories that have the issue<br>tracker enabled.
      summary: Atlassian List Components
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianListComponents
  /repositories/{workspace}/{repo_slug}/components/{component_id}:
    get:
      tags:
      - Issue Tracker
      description: Returns the specified issue tracker component object.
      summary: Atlassian Get A Component For Issues
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianGetAComponentForIssues
  /repositories/{workspace}/{repo_slug}/issues:
    get:
      tags:
      - Issue Tracker
      description: Returns the issues in the issue tracker.
      summary: Atlassian List Issues
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianListIssues
    post:
      tags:
      - Issue Tracker
      description: Creates a new issue.<br><br>This call requires authentication. Private repositories or private<br>issue trackers require the caller to authenticate with an account that<br>has appropriate authorization.<br><br>The authenticated user is used for the issue's `reporter` field.
      summary: Atlassian Create An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianCreateAnIssue
  /repositories/{workspace}/{repo_slug}/issues/export:
    post:
      tags:
      - Issue Tracker
      description: A POST request to this endpoint initiates a new background celery task that archives the repo's issues.<br><br>When the job has been accepted, it will return a 202 (Accepted) along with a unique url to this job in the<br>'Location' response header. This url is the endpoint for where the user can obtain their zip files."
      summary: Atlassian Export Issues
      security:
      - oauth2:
        - issue
        - repository:admin
      - basic: []
      - api_key: []
      operationId: atlassianExportIssues
  /repositories/{workspace}/{repo_slug}/issues/export/{repo_name}-issues-{task_id}.zip:
    get:
      tags:
      - Issue Tracker
      description: This endpoint is used to poll for the progress of an issue export<br>job and return the zip file after the job is complete.<br>As long as the job is running, this will return a 202 response<br>with in the response body a description of the current status.<br><br>After the job has been scheduled, but before it starts executing, the endpoint<br>returns a 202 response with status `ACCEPTED`.<br><br>Once it starts running, it is a 202 response with status `STARTED` and progress fi[...]
      summary: Atlassian Check Issue Export Status
      security:
      - oauth2:
        - issue
        - repository:admin
      - basic: []
      - api_key: []
      operationId: atlassianCheckIssueExportStatus
  /repositories/{workspace}/{repo_slug}/issues/import:
    get:
      tags:
      - Issue Tracker
      description: When using GET, this endpoint reports the status of the current import task.<br><br>After the job has been scheduled, but before it starts executing, the endpoint<br>returns a 202 response with status `ACCEPTED`.<br><br>Once it starts running, it is a 202 response with status `STARTED` and progress filled.<br><br>After it is finished, it becomes a 200 response with status `SUCCESS` or `FAILURE`.
      summary: Atlassian Check Issue Import Status
      security:
      - oauth2:
        - issue:write
        - repository:admin
      - basic: []
      - api_key: []
      operationId: atlassianCheckIssueImportStatus
    post:
      tags:
      - Issue Tracker
      description: A POST request to this endpoint will import the zip file given by the archive parameter into the repository. All<br>existing issues will be deleted and replaced by the contents of the imported zip file.<br><br>Imports are done through a multipart/form-data POST. There is one valid and required form field, with the name<br>"archive," which needs to be a file field:<br><br>```<br>$ curl -u  -X POST -F archive=@/path/to/file.zip https://api.bitbucket.org/2.0/repositories///issues[...]
      summary: Atlassian Import Issues
      security:
      - oauth2:
        - issue:write
        - repository:admin
      - basic: []
      - api_key: []
      operationId: atlassianImportIssues
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}:
    delete:
      tags:
      - Issue Tracker
      description: Deletes the specified issue. This requires write access to the<br>repository.
      summary: Atlassian Delete An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianDeleteAnIssue
    get:
      tags:
      - Issue Tracker
      description: Returns the specified issue.
      summary: Atlassian Get An Issue
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianGetAnIssue
    put:
      tags:
      - Issue Tracker
      description: 'Modifies the issue.<br><br>```<br>$ curl https://api.bitbucket.org/2.0/repostories/evzijst/dogslow/issues/123 \<br>  -u evzijst -s -X PUT -H ''Content-Type: application/json'' \<br>  -d ''{<br>  "title": "Updated title",<br>  "assignee": {<br>    "account_id": "5d5355e8c6b9320d9ea5b28d"<br>  },<br>  "priority": "minor",<br>  "version": {<br>    "name": "1.0"<br>  },<br>  "component": null<br>}''<br>```<br><br>This example changes the `title`, `assignee`, `priority` and the<br[...]'
      summary: Atlassian Update An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianUpdateAnIssue
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/attachments:
    get:
      tags:
      - Issue Tracker
      description: Returns all attachments for this issue.<br><br>This returns the files' meta data. This does not return the files'<br>actual contents.<br><br>The files are always ordered by their upload date.
      summary: Atlassian List Attachments For An Issue
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianListAttachmentsForAnIssue
    post:
      tags:
      - Issue Tracker
      description: Upload new issue attachments.<br><br>To upload files, perform a `multipart/form-data` POST containing one<br>or more file fields.<br><br>When a file is uploaded with the same name as an existing attachment,<br>then the existing file will be replaced.
      summary: Atlassian Upload An Attachment To An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianUploadAnAttachmentToAnIssue
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/attachments/{path}:
    delete:
      tags:
      - Issue Tracker
      description: Deletes an attachment.
      summary: Atlassian Delete An Attachment For An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianDeleteAnAttachmentForAnIssue
    get:
      tags:
      - Issue Tracker
      description: Returns the contents of the specified file attachment.<br><br>Note that this endpoint does not return a JSON response, but instead<br>returns a redirect pointing to the actual file that in turn will return<br>the raw contents.<br><br>The redirect URL contains a one-time token that has a limited lifetime.<br>As a result, the link should not be persisted, stored, or shared.
      summary: Atlassian Get Attachment For An Issue
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianGetAttachmentForAnIssue
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/changes:
    get:
      tags:
      - Issue Tracker
      description: Returns the list of all changes that have been made to the specified<br>issue. Changes are returned in chronological order with the oldest<br>change first.<br><br>Each time an issue is edited in the UI or through the API, an immutable<br>change record is created under the `/issues/123/changes` endpoint. It<br>also has a comment associated with the change.<br><br>Note that this operation is changing significantly, due to privacy changes.<br>See the [announcement](https://develo[...]
      summary: Atlassian List Changes On An Issue
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianListChangesOnAnIssue
    post:
      tags:
      - Issue Tracker
      description: 'Makes a change to the specified issue.<br><br>For example, to change an issue''s state and assignee, create a new<br>change object that modifies these fields:<br><br>```<br>curl https://api.bitbucket.org/2.0/site/master/issues/1234/changes \<br>  -s -u evzijst -X POST -H "Content-Type: application/json" \<br>  -d ''{<br>    "changes": {<br>      "assignee_account_id": {<br>        "new": "557058:c0b72ad0-1cb5-4018-9cdc-0cde8492c443"<br>      },<br>      "state": {<br>        [...]'
      summary: Atlassian Modify The State Of An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianModifyTheStateOfAnIssue
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/changes/{change_id}:
    get:
      tags:
      - Issue Tracker
      description: Returns the specified issue change object.<br><br>This resource is only available on repositories that have the issue<br>tracker enabled.
      summary: Atlassian Get Issue Change Object
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianGetIssueChangeObject
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments:
    get:
      tags:
      - Issue Tracker
      description: Returns a paginated list of all comments that were made on the<br>specified issue.<br><br>The default sorting is oldest to newest and can be overridden with<br>the `sort` query parameter.<br><br>This endpoint also supports filtering and sorting of the results. See<br>[filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more details.
      summary: Atlassian List Comments On An Issue
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianListCommentsOnAnIssue
    post:
      tags:
      - Issue Tracker
      description: 'Creates a new issue comment.<br><br>```<br>$ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/ \<br>  -X POST -u evzijst \<br>  -H ''Content-Type: application/json'' \<br>  -d ''{"content": {"raw": "Lorem ipsum."}}''<br>```'
      summary: Atlassian Create A Comment On An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianCreateACommentOnAnIssue
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments/{comment_id}:
    delete:
      tags:
      - Issue Tracker
      description: Deletes the specified comment.
      summary: Atlassian Delete A Comment On An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianDeleteACommentOnAnIssue
    get:
      tags:
      - Issue Tracker
      description: Returns the specified issue comment object.
      summary: Atlassian Get A Comment On An Issue
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianGetACommentOnAnIssue
    put:
      tags:
      - Issue Tracker
      description: 'Updates the content of the specified issue comment. Note that only<br>the `content.raw` field can be modified.<br><br>```<br>$ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/5728901 \<br>  -X PUT -u evzijst \<br>  -H ''Content-Type: application/json'' \<br>  -d ''{"content": {"raw": "Lorem ipsum."}''<br>```'
      summary: Atlassian Update A Comment On An Issue
      security:
      - oauth2:
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianUpdateACommentOnAnIssue
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/vote:
    delete:
      tags:
      - Issue Tracker
      description: Retract your vote.
      summary: Atlassian Remove Vote For An Issue
      security:
      - oauth2:
        - account:write
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianRemoveVoteForAnIssue
    get:
      tags:
      - Issue Tracker
      description: Check whether the authenticated user has voted for this issue.<br>A 204 status code indicates that the user has voted, while a 404<br>implies they haven't.
      summary: Atlassian Check If Current User Voted For An Issue
      security:
      - oauth2:
        - account
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianCheckIfCurrentUserVotedForAnIssue
    put:
      tags:
      - Issue Tracker
      description: Vote for this issue.<br><br>To cast your vote, do an empty PUT. The 204 status code indicates that<br>the operation was successful.
      summary: Atlassian Vote For An Issue
      security:
      - oauth2:
        - account:write
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianVoteForAnIssue
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/watch:
    delete:
      tags:
      - Issue Tracker
      description: Stop watching this issue.
      summary: Atlassian Stop Watching An Issue
      security:
      - oauth2:
        - account:write
        - issue:write
      - basic: []
      - api_key: []
      operationId: atlassianStopWatchingAnIssue
    get:
      tags:
      - Issue Tracker
      description: Indicated whether or not the authenticated user is watching this<br>issue.
      summary: Atlassian Check If Current User Is Watching A Issue
      security:
      - oauth2:
        - account
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianCheckIfCurrentUserIsWatchingAIssue
    put:
      tags:
      - Issue Tracker
      description: Start watching this issue.<br><br>To start watching this issue, do an empty PUT. The 204 status code<br>indicates that the operation was successful.
      summary: Atlassian Watch An Issue
      security:
      - oauth2:
        - account:write
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianWatchAnIssue
  /repositories/{workspace}/{repo_slug}/milestones:
    get:
      tags:
      - Issue Tracker
      description: Returns the milestones that have been defined in the issue tracker.<br><br>This resource is only available on repositories that have the issue<br>tracker enabled.
      summary: Atlassian List Milestones
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianListMilestones
  /repositories/{workspace}/{repo_slug}/milestones/{milestone_id}:
    get:
      tags:
      - Issue Tracker
      description: Returns the specified issue tracker milestone object.
      summary: Atlassian Get A Milestone
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianGetAMilestone
  /repositories/{workspace}/{repo_slug}/versions:
    get:
      tags:
      - Issue Tracker
      description: Returns the versions that have been defined in the issue tracker.<br><br>This resource is only available on repositories that have the issue<br>tracker enabled.
      summary: Atlassian List Defined Versions For Issues
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianListDefinedVersionsForIssues
  /repositories/{workspace}/{repo_slug}/versions/{version_id}:
    get:
      tags:
      - Issue Tracker
      description: Returns the specified issue tracker version object.
      summary: Atlassian Get A Defined Version For Issues
      security:
      - oauth2:
        - issue
      - basic: []
      - api_key: []
      operationId: atlassianGetADefinedVersionForIssues
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.