openapi: 3.1.0
info:
  title: Atlassian Admin Account Project Role Actors API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Project Role Actors
paths:
  /rest/api/3/project/{projectIdOrKey}/role/{id}:
    delete:
      deprecated: false
      description: Deletes actors from a project role for the project.<br><br>To remove default actors from the project role, use [Delete default actors from project role](#api-rest-api-3-role-id-actors-delete).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteactor
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      - {}
      summary: Atlassian Delete Actors From Project Role
      tags:
      - Project Role Actors
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:project-role:jira
        state: Beta
      x-atlassian-connect-scope: PROJECT_ADMIN
    post:
      deprecated: false
      description: Adds actors to a project role for the project.<br><br>To replace all actors for the project, use [Set actors for project role](#api-rest-api-3-project-projectIdOrKey-role-id-put).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAddactorusers
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      - {}
      summary: Atlassian Add Actors To Project Role
      tags:
      - Project Role Actors
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user:jira
        - read:group:jira
        - read:project-role:jira
        - read:project:jira
        - write:project-role:jira
        - read:avatar:jira
        - read:project-category:jira
        state: Beta
      x-atlassian-connect-scope: PROJECT_ADMIN
    put:
      deprecated: false
      description: Sets the actors for a project role for a project, replacing all existing actors.<br><br>To add actors to the project without overwriting the existing list, use [Add actors to project role](#api-rest-api-3-project-projectIdOrKey-role-id-post).<br><br>**[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianSetactors
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      - {}
      summary: Atlassian Set Actors For Project Role
      tags:
      - Project Role Actors
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user:jira
        - read:group:jira
        - read:project-role:jira
        - read:project:jira
        - write:project-role:jira
        - read:avatar:jira
        - read:project-category:jira
        state: Beta
      x-atlassian-connect-scope: PROJECT_ADMIN
  /rest/api/3/role/{id}/actors:
    delete:
      deprecated: false
      description: Deletes the [default actors](#api-rest-api-3-resolution-get) from a project role. You may delete a group or user, but you cannot delete a group and a user in the same request.<br><br>Changing a project role's default actors does not affect project role members for projects already created.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteprojectroleactorsfromrole
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Default Actors From Project Role
      tags:
      - Project Role Actors
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:project-role:jira
        - read:user:jira
        - read:group:jira
        - read:project-role:jira
        - read:project:jira
        - read:avatar:jira
        - read:project-category:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns the [default actors](#api-rest-api-3-resolution-get) for the project role.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetprojectroleactorsforrole
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Default Actors For Project Role
      tags:
      - Project Role Actors
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user:jira
        - read:group:jira
        - read:project-role:jira
        - read:project:jira
        - read:avatar:jira
        - read:project-category:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    post:
      deprecated: false
      description: Adds [default actors](#api-rest-api-3-resolution-get) to a role. You may add groups or users, but you cannot add groups and users in the same request.<br><br>Changing a project role's default actors does not affect project role members for projects already created.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAddprojectroleactorstorole
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Add Default Actors To Project Role
      tags:
      - Project Role Actors
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user:jira
        - read:group:jira
        - read:project-role:jira
        - read:project:jira
        - write:project-role:jira
        - read:avatar:jira
        - read:project-category:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.