openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Security Schemes API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Security Schemes
paths:
  /rest/api/3/issuesecurityschemes/level:
    get:
      deprecated: false
      description: 'Returns a [paginated](#pagination) list of issue security levels.<br><br>Only issue security levels in the context of classic projects are returned.<br><br>Filtering using IDs is inclusive: if you specify both security scheme IDs and level IDs, the result will include both specified issue security levels and all issue security levels from the specified schemes.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.[...]'
      operationId: atlassianGetsecuritylevels
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Security Levels
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-security-level:jira
        - read:issue-security-scheme:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/level/default:
    put:
      deprecated: false
      description: Sets default issue security levels for schemes.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianSetdefaultlevels
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Set Default Issue Security Levels
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/level/member:
    get:
      deprecated: false
      description: 'Returns a [paginated](#pagination) list of issue security level members.<br><br>Only issue security level members in the context of classic projects are returned.<br><br>Filtering using parameters is inclusive: if you specify both security scheme IDs and level IDs, the result will include all issue security level members from the specified schemes and levels.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.co[...]'
      operationId: atlassianGetsecuritylevelmembers
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Issue Security Level Members
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-security-level:jira
        - read:issue-security-scheme:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/project:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) mapping of projects that are using security schemes. You can provide either one or multiple security scheme IDs or project IDs to filter by. If you don't provide any, this will return a list of all mappings. Only issue security schemes in the context of classic projects are supported. **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianSearchprojectsusingsecurityschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Projects Using Issue Security Schemes
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Associates an issue security scheme with a project and remaps security levels of issues to the new levels, if provided.<br><br>This operation is [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAssociateschemestoprojects
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Associate Security Scheme To Project
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/search:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of issue security schemes.  <br>If you specify the project ID parameter, the result will contain issue security schemes and related project IDs you filter by. Use \{@link IssueSecuritySchemeResource\#searchProjectsUsingSecuritySchemes(String, String, Set, Set)\} to obtain all projects related to scheme.<br><br>Only issue security schemes in the context of classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Ad[...]
      operationId: atlassianSearchsecurityschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Search Issue Security Schemes
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-security-level:jira
        - read:issue-security-scheme:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/{id}:
    get:
      deprecated: false
      description: Returns an issue security scheme along with its security levels.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).<br> *  *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for a project that uses the requested issue security scheme.
      operationId: atlassianGetissuesecurityscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      summary: Atlassian Get Issue Security Scheme
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-security-level:jira
        - read:issue-security-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates the issue security scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdateissuesecurityscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Issue Security Scheme
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/{schemeId}:
    delete:
      deprecated: false
      description: Deletes an issue security scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeletesecurityscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Issue Security Scheme
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/{schemeId}/level:
    put:
      deprecated: false
      description: Adds levels and levels' members to the issue security scheme. You can add up to 100 levels per request.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAddsecuritylevel
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Add Issue Security Levels
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/{schemeId}/level/{levelId}:
    delete:
      deprecated: false
      description: Deletes an issue security level.<br><br>This operation is [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianRemovelevel
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Remove Issue Security Level
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates the issue security level.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatesecuritylevel
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Issue Security Level
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/{schemeId}/level/{levelId}/member:
    put:
      deprecated: false
      description: Adds members to the issue security level. You can add up to 100 members per request.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAddsecuritylevelmembers
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Add Issue Security Level Members
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes/{schemeId}/level/{levelId}/member/{memberId}:
    delete:
      deprecated: false
      description: Removes an issue security level member from an issue security scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianRemovememberfromsecuritylevel
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Remove Member From Issue Security Level
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/issuesecurityschemes:
    get:
      deprecated: false
      description: Returns all [issue security schemes](https://confluence.atlassian.com/x/J4lKLg).<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetissuesecurityschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      summary: Atlassian Get Issue Security Schemes
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-security-level:jira
        - read:issue-security-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    post:
      deprecated: false
      description: Creates a security scheme with security scheme levels and levels' members. You can create up to 100 security scheme levels and security scheme levels' members per request.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreateissuesecurityscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Issue Security Scheme
      tags:
      - Issue Security Schemes
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.