openapi: 3.2.0
info:
  title: Atlassian Commits API
  version: '2.0'
  contact:
    name: Bitbucket Support
    url: https://support.atlassian.com/bitbucket-cloud/
    email: support@bitbucket.org
  termsOfService: https://www.atlassian.com/legal/customer-agreement
  description: 'Operations tagged Commits across 2 of this provider''s published API definitions: bitbucket-openapi-original.yml, bitbucket-swagger.json. Each path carries the servers of the definition it was published in.'
servers:
- url: https://api.bitbucket.org/2.0
tags:
- name: Commits
  description: 'These are the repository''s commits. They are paginated and returned in

    reverse chronological order, similar to the output of git log.'
paths:
  /repositories/{workspace}/{repo_slug}/commit/{commit}:
    get:
      tags:
      - Commits
      description: Returns the specified commit.
      summary: Atlassian Get A Commit
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianGetACommit
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commit/{commit}/approve:
    delete:
      tags:
      - Commits
      description: 'Redact the authenticated user''s approval of the specified commit.


        This operation is only available to users that have explicit access to

        the repository. In contrast, just the fact that a repository is

        publicly accessible to users does not give them the ability to approve

        commits.'
      summary: Atlassian Unapprove A Commit
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - write:repository:bitbucket
      operationId: atlassianUnapproveACommit
    post:
      tags:
      - Commits
      description: 'Approve the specified commit as the authenticated user.


        This operation is only available to users that have explicit access to

        the repository. In contrast, just the fact that a repository is

        publicly accessible to users does not give them the ability to approve

        commits.'
      summary: Atlassian Approve A Commit
      security:
      - oauth2:
        - repository:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
        - write:repository:bitbucket
      operationId: atlassianApproveACommit
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commit/{commit}/comments:
    get:
      tags:
      - Commits
      description: 'Returns the commit''s comments.


        This includes both global and inline comments.


        The default sorting is oldest to newest and can be overridden with

        the `sort` query parameter.'
      summary: Atlassian List A Commit S Comments
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianListACommitSComments
    post:
      tags:
      - Commits
      description: 'Creates new comment on the specified commit.


        To post a reply to an existing comment, include the `parent.id` field:


        ```

        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/commit/db9ba1e031d07a02603eae0e559a7adc010257fc/comments/ \

        -X POST -u evzijst \

        -H ''Content-Type: application/json'' \

        -d ''{"content": {"raw": "One more thing!"},

        "parent": {"id": 5728901}}''

        ```'
      summary: Atlassian Create Comment For A Commit
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianCreateCommentForACommit
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commit/{commit}/comments/{comment_id}:
    delete:
      tags:
      - Commits
      description: 'Deletes the specified commit comment.


        Note that deleting comments that have visible replies that point to

        them will not really delete the resource. This is to retain the integrity

        of the original comment tree. Instead, the `deleted` element is set to

        `true` and the content is blanked out. The comment will continue to be

        returned by the collections and self endpoints.'
      summary: Atlassian Delete A Commit Comment
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianDeleteACommitComment
    get:
      tags:
      - Commits
      description: Returns the specified commit comment.
      summary: Atlassian Get A Commit Comment
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianGetACommitComment
    put:
      tags:
      - Commits
      description: 'Used to update the contents of a comment. Only the content of the comment can be updated.


        ```

        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/commit/7f71b5/comments/5728901 \

        -X PUT -u evzijst \

        -H ''Content-Type: application/json'' \

        -d ''{"content": {"raw": "One more thing!"}''

        ```'
      summary: Atlassian Update A Commit Comment
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianUpdateACommitComment
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commits:
    get:
      tags:
      - Commits
      description: 'These are the repository''s commits. They are paginated and returned

        in reverse chronological order, similar to the output of `git log`.

        Like these tools, the DAG can be filtered.


        #### GET /repositories/{workspace}/{repo_slug}/commits/


        Returns all commits in the repo in topological order (newest commit

        first). All branches and tags are included (similar to

        `git log --all`).


        #### GET /repositories/{workspace}/{repo_slug}/commits/?exclude=master


        Returns all commits in the repo that are not on master

        (similar to `git log --all ^master`).


        #### GET /repositories/{workspace}/{repo_slug}/commits/?include=foo&include=bar&exclude=fu&exclude=fubar


        Returns all commits that are on refs `foo` or `bar`, but not on `fu` or

        `fubar` (similar to `git log foo bar ^fu ^fubar`).


        An optional `path` parameter can be specified that will limit the

        results to commits that affect that path. `path` can either be a file

        or a directory. If a directory is specified, commits are returned that

        have modified any file in the directory tree rooted by `path`. It is

        important to note that if the `path` parameter is specified, the commits

        returned by this endpoint may no longer be a DAG, parent commits that

        do not modify the path will be omitted from the response.


        #### GET /repositories/{workspace}/{repo_slug}/commits/?path=README.md&include=foo&include=bar&exclude=master


        Returns all commits that are on refs `foo` or `bar`, but not on `master`

        that changed the file README.md.


        #### GET /repositories/{workspace}/{repo_slug}/commits/?path=src/&include=foo&include=bar&exclude=master


        Returns all commits that are on refs `foo` or `bar`, but not on `master`

        that changed to a file in any file in the directory src or its children.


        Because the response could include a very large number of commits, it

        is paginated. Follow the ''next'' link in the response to navigate to the

        next page of commits. As with other paginated resources, do not

        construct your own links.


        When the include and exclude parameters are more than can fit in a

        query string, clients can use a `x-www-form-urlencoded` POST instead.'
      summary: Atlassian List Commits
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianListCommits
    post:
      tags:
      - Commits
      description: 'Identical to `GET /repositories/{workspace}/{repo_slug}/commits`,

        except that POST allows clients to place the include and exclude

        parameters in the request body to avoid URL length issues.


        **Note that this resource does NOT support new commit creation.**'
      summary: Atlassian List Commits With Include Exclude
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianListCommitsWithIncludeExclude
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commits/{revision}:
    get:
      tags:
      - Commits
      description: 'These are the repository''s commits. They are paginated and returned

        in reverse chronological order, similar to the output of `git log`.

        Like these tools, the DAG can be filtered.


        #### GET /repositories/{workspace}/{repo_slug}/commits/master


        Returns all commits on ref `master` (similar to `git log master`).


        #### GET /repositories/{workspace}/{repo_slug}/commits/dev?include=foo&exclude=master


        Returns all commits on ref `dev` or `foo`, except those that are reachable on

        `master` (similar to `git log dev foo ^master`).


        An optional `path` parameter can be specified that will limit the

        results to commits that affect that path. `path` can either be a file

        or a directory. If a directory is specified, commits are returned that

        have modified any file in the directory tree rooted by `path`. It is

        important to note that if the `path` parameter is specified, the commits

        returned by this endpoint may no longer be a DAG, parent commits that

        do not modify the path will be omitted from the response.


        #### GET /repositories/{workspace}/{repo_slug}/commits/dev?path=README.md&include=foo&include=bar&exclude=master


        Returns all commits that are on refs `dev` or `foo` or `bar`, but not on `master`

        that changed the file README.md.


        #### GET /repositories/{workspace}/{repo_slug}/commits/dev?path=src/&include=foo&exclude=master


        Returns all commits that are on refs `dev` or `foo`, but not on `master`

        that changed to a file in any file in the directory src or its children.


        Because the response could include a very large number of commits, it

        is paginated. Follow the ''next'' link in the response to navigate to the

        next page of commits. As with other paginated resources, do not

        construct your own links.


        When the include and exclude parameters are more than can fit in a

        query string, clients can use a `x-www-form-urlencoded` POST instead.'
      summary: Atlassian List Commits For Revision
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianListCommitsForRevision
    post:
      tags:
      - Commits
      description: 'Identical to `GET /repositories/{workspace}/{repo_slug}/commits/{revision}`,

        except that POST allows clients to place the include and exclude

        parameters in the request body to avoid URL length issues.


        **Note that this resource does NOT support new commit creation.**'
      summary: Atlassian List Commits For Revision Using Include Exclude
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianListCommitsForRevisionUsingIncludeExclude
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/diff/{spec}:
    get:
      tags:
      - Commits
      description: 'Produces a raw git-style diff.


        #### Single commit spec


        If the `spec` argument to this API is a single commit, the diff is

        produced against the first parent of the specified commit.


        #### Two commit spec


        Two commits separated by `..` may be provided as the `spec`, e.g.,

        `3a8b42..9ff173`. When two commits are provided and the `topic` query

        parameter is true, this API produces a 2-way three dot diff.

        This is the diff between source commit and the merge base of the source

        commit and the destination commit. When the `topic` query param is false,

        a simple git-style diff is produced.


        The two commits are interpreted as follows:


        * First commit: the commit containing the changes we wish to preview

        * Second commit: the commit representing the state to which we want to

        compare the first commit

        * **Note**: This is the opposite of the order used in `git diff`.


        #### Comparison to patches


        While similar to patches, diffs:


        * Don''t have a commit header (username, commit message, etc)

        * Support the optional `path=foo/bar.py` query param to filter

        the diff to just that one file diff


        #### Response


        The raw diff is returned as-is, in whatever encoding the files in the

        repository use. It is not decoded into unicode. As such, the

        content-type is `text/plain`.'
      summary: Atlassian Compare Two Commits
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianCompareTwoCommits
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/diffstat/{spec}:
    get:
      tags:
      - Commits
      description: 'Produces a response in JSON format with a record for every path

        modified, including information on the type of the change and the

        number of lines added and removed.


        #### Single commit spec


        If the `spec` argument to this API is a single commit, the diff is

        produced against the first parent of the specified commit.


        #### Two commit spec


        Two commits separated by `..` may be provided as the `spec`, e.g.,

        `3a8b42..9ff173`. When two commits are provided and the `topic` query

        parameter is true, this API produces a 2-way three dot diff.

        This is the diff between source commit and the merge base of the source

        commit and the destination commit. When the `topic` query param is false,

        a simple git-style diff is produced.


        The two commits are interpreted as follows:


        * First commit: the commit containing the changes we wish to preview

        * Second commit: the commit representing the state to which we want to

        compare the first commit

        * **Note**: This is the opposite of the order used in `git diff`.'
      summary: Atlassian Compare Two Commit Diff Stats
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianCompareTwoCommitDiffStats
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/merge-base/{revspec}:
    get:
      tags:
      - Commits
      description: 'Returns the best common ancestor between two commits, specified in a revspec

        of 2 commits (e.g. 3a8b42..9ff173).


        If more than one best common ancestor exists, only one will be returned. It is

        unspecified which will be returned.'
      summary: Atlassian Get The Common Ancestor Between Two Commits
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianGetTheCommonAncestorBetweenTwoCommits
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/patch/{spec}:
    get:
      tags:
      - Commits
      description: 'Produces a raw patch for a single commit (diffed against its first

        parent), or a patch-series for a revspec of 2 commits (e.g.

        `3a8b42..9ff173` where the first commit represents the source and the

        second commit the destination).


        In case of the latter (diffing a revspec), a patch series is returned

        for the commits on the source branch (`3a8b42` and its ancestors in

        our example).


        While similar to diffs, patches:


        * Have a commit header (username, commit message, etc)

        * Do not support the `path=foo/bar.py` query parameter


        The raw patch is returned as-is, in whatever encoding the files in the

        repository use. It is not decoded into unicode. As such, the

        content-type is `text/plain`.'
      summary: Atlassian Get A Patch For Two Commits
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      operationId: atlassianGetAPatchForTwoCommits
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commit/{commit}/reports:
    get:
      tags:
      - Commits
      description: Returns a paginated list of Reports linked to this commit.
      summary: List reports
      operationId: getReportsForCommit
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}:
    put:
      tags:
      - Commits
      description: 'Creates or updates a report for the specified commit.

        To upload a report, make sure to generate an ID that is unique across all reports for that commit. If you want to use an existing id from your own system, we recommend prefixing it with your system''s name to avoid collisions, for example, mySystem-001.


        ### Sample cURL request:

        ```

        curl --request PUT ''https://api.bitbucket.org/2.0/repositories///commit//reports/mysystem-001'' \

        --header ''Content-Type: application/json'' \

        --data-raw ''{

        "title": "Security scan report",

        "details": "This pull request introduces 10 new dependency vulnerabilities.",

        "report_type": "SECURITY",

        "reporter": "mySystem",

        "link": "http://www.mysystem.com/reports/001",

        "result": "FAILED",

        "data": [

        {

        "title": "Duration (seconds)",

        "type": "DURATION",

        "value": 14

        },

        {

        "title": "Safe to merge?",

        "type": "BOOLEAN",

        "value": false

        }

        ]

        }''

        ```


        ### Possible field values:

        report_type: SECURITY, COVERAGE, TEST, BUG

        result: PASSED, FAILED, PENDING

        data.type: BOOLEAN, DATE, DURATION, LINK, NUMBER, PERCENTAGE, TEXT


        #### Data field formats

        | Type Field | Value Field Type | Value Field Display |

        |:--------------|:------------------|:--------------------|

        | None/ Omitted | Number, String or Boolean (not an array or object) | Plain text |

        | BOOLEAN | Boolean | The value will be read as a JSON boolean and displayed as ''Yes'' or ''No''. |

        | DATE | Number | The value will be read as a JSON number in the form of a Unix timestamp (milliseconds) and will be displayed as a relative date if the date is less than one week ago, otherwise it will be displayed as an absolute date. |

        | DURATION | Number | The value will be read as a JSON number in milliseconds and will be displayed in a human readable duration format. |

        | LINK | Object: `{"text": "Link text here", "href": "https://link.to.annotation/in/external/tool"}` | The value will be read as a JSON object containing the fields "text" and "href" and will be displayed as a clickable link on the report. |

        | NUMBER | Number | The value will be read as a JSON number and large numbers will be displayed in a human readable format (e.g. 14.3k). |

        | PERCENTAGE | Number (between 0 and 100) | The value will be read as a JSON number between 0 and 100 and will be displayed with a percentage sign. |

        | TEXT | String | The value will be read as a JSON string and will be displayed as-is |


        Please refer to the Code Insights documentation for more information.'
      operationId: createOrUpdateReport
      summary: Create or update a report
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    get:
      tags:
      - Commits
      description: Returns a single Report matching the provided ID.
      summary: Get a report
      operationId: getReport
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    delete:
      tags:
      - Commits
      description: Deletes a single Report matching the provided ID.
      summary: Delete a report
      operationId: deleteReport
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations:
    get:
      tags:
      - Commits
      description: Returns a paginated list of Annotations for a specified report.
      summary: List annotations
      operationId: getAnnotationsForReport
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    post:
      tags:
      - Commits
      description: 'Bulk upload of annotations.

        Annotations are individual findings that have been identified as part of a report, for example, a line of code that represents a vulnerability. These annotations can be attached to a specific file and even a specific line in that file, however, that is optional. Annotations are not mandatory and a report can contain up to 1000 annotations.


        Add the annotations you want to upload as objects in a JSON array and make sure each annotation has the external_id field set to a unique value. If you want to use an existing id from your own system, we recommend prefixing it with your system''s name to avoid collisions, for example, mySystem-annotation001. The external id can later be used to identify the report as an alternative to the generated UUID. You can upload up to 100 annotations per POST request.


        ### Sample cURL request:

        ```

        curl --location ''https://api.bitbucket.org/2.0/repositories///commit//reports/mysystem-001/annotations'' \

        --header ''Content-Type: application/json'' \

        --data-raw ''[

        {

        "external_id": "mysystem-annotation001",

        "title": "Security scan report",

        "annotation_type": "VULNERABILITY",

        "summary": "This line represents a security threat.",

        "severity": "HIGH",

        "path": "my-service/src/main/java/com/myCompany/mysystem/logic/Main.java",

        "line": 42

        },

        {

        "external_id": "mySystem-annotation002",

        "title": "Bug report",

        "annotation_type": "BUG",

        "result": "FAILED",

        "summary": "This line might introduce a bug.",

        "severity": "MEDIUM",

        "path": "my-service/src/main/java/com/myCompany/mysystem/logic/Helper.java",

        "line": 13

        }

        ]''

        ```


        ### Possible field values:

        annotation_type: VULNERABILITY, CODE_SMELL, BUG

        result: PASSED, FAILED, IGNORED, SKIPPED

        severity: HIGH, MEDIUM, LOW, CRITICAL


        Please refer to the Code Insights documentation for more information.'
      operationId: bulkCreateOrUpdateAnnotations
      summary: Bulk create or update annotations
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations/{annotationId}:
    get:
      tags:
      - Commits
      description: Returns a single Annotation matching the provided ID.
      summary: Get an annotation
      operationId: getAnnotation
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    put:
      tags:
      - Commits
      description: 'Creates or updates an individual annotation for the specified report.

        Annotations are individual findings that have been identified as part of a report, for example, a line of code that represents a vulnerability. These annotations can be attached to a specific file and even a specific line in that file, however, that is optional. Annotations are not mandatory and a report can contain up to 1000 annotations.


        Just as reports, annotation needs to be uploaded with a unique ID that can later be used to identify the report as an alternative to the generated UUID. If you want to use an existing id from your own system, we recommend prefixing it with your system''s name to avoid collisions, for example, mySystem-annotation001.


        ### Sample cURL request:

        ```

        curl --request PUT ''https://api.bitbucket.org/2.0/repositories///commit//reports/mySystem-001/annotations/mysystem-annotation001'' \

        --header ''Content-Type: application/json'' \

        --data-raw ''{

        "title": "Security scan report",

        "annotation_type": "VULNERABILITY",

        "summary": "This line represents a security thread.",

        "severity": "HIGH",

        "path": "my-service/src/main/java/com/myCompany/mysystem/logic/Main.java",

        "line": 42

        }''

        ```


        ### Possible field values:

        annotation_type: VULNERABILITY, CODE_SMELL, BUG

        result: PASSED, FAILED, IGNORED, SKIPPED

        severity: HIGH, MEDIUM, LOW, CRITICAL


        Please refer to the Code Insights documentation for more information.'
      operationId: createOrUpdateAnnotation
      summary: Create or update an annotation
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    delete:
      tags:
      - Commits
      description: Deletes a single Annotation matching the provided ID.
      summary: Delete an annotation
      operationId: deleteAnnotation
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
    servers:
    - url: https://api.bitbucket.org/2.0
  /repositories/{workspace}/{repo_slug}/file-conflicts/{spec}:
    get:
      tags:
      - Commits
      summary: Get file conflicts for a commit spec
      security:
      - oauth2:
        - repository
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:repository:bitbucket
      x-atlassian-auth-types:
      - forge-oauth2
      - api-token
      operationId: getRepositoriesByWorkspaceByRepoSlugFileConflictsBySpec
      x-operation-id-source: derived
    servers:
    - url: https://api.bitbucket.org/2.0
components:
  securitySchemes:
    basic:
      type: http
      description: Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617) (Digest not supported). Note that Basic Auth is available only with username and app password as credentials.
      scheme: basic
    oauth2:
      type: oauth2
      description: OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749).
      flows:
        authorizationCode:
          authorizationUrl: https://bitbucket.org/site/oauth2/authorize
          tokenUrl: https://bitbucket.org/site/oauth2/access_token
          scopes:
            email: Read your account's primary email address
            account: Read your account information
            account:write: Read and modify your account information
            team: Read your team membership information
            team:write: Read and modify your team membership information
            repository: Read your repositories
            repository:write: Read and modify your repositories
            repository:admin: Administer your repositories
            repository:delete: Delete your repositories
            project: Read your workspace's project settings and read repositories contained within your workspace's projects
            project:admin: Read and modify settings for projects in your workspace
            pipeline: Access your repositories' build pipelines
            pipeline:write: Access and rerun your repositories' build pipelines
            pipeline:variable: Access your repositories' build pipelines and configure their variables
            runner: Access your workspaces/repositories' runners
            runner:write: Access and edit your workspaces/repositories' runners
            pullrequest: Read your repositories and their pull requests
            pullrequest:write: Read and modify your repositories and their pull requests
            webhook: Read and modify your repositories' webhooks
            issue: Read your repositories' issues
            issue:write: Read and modify your repositories' issues
            snippet: Read your snippets
            snippet:write: Read and modify your snippets
            wiki: Read and modify your repositories' wikis
    api_key:
      name: Authorization
      type: apiKey
      description: API Keys can be used as Basic HTTP Authentication credentials and provide a substitute for the account's actual username and password. API Keys are only available to team accounts and there is only 1 key per account. API Keys do not support scopes and have therefore access to all contents of the account.
      in: header
x-refined-from:
- bitbucket-openapi-original.yml
- bitbucket-swagger.json
