openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Worklogs API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Worklogs
paths:
  /rest/api/3/issue/{issueIdOrKey}/worklog:
    get:
      deprecated: false
      description: Returns worklogs for an issue, starting from the oldest worklog or from the worklog started on or after a date and time.<br><br>Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** Workloads are only returned where the user has:<br><br> *  *Browse project[...]
      operationId: atlassianGetissueworklog
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Issue Worklogs
      tags:
      - Issue Worklogs
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:group:jira
        - read:issue-worklog:jira
        - read:issue-worklog.property:jira
        - read:project-role:jira
        - read:user:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Adds a worklog to an issue.<br><br>Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* and *Work on issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issu[...]
      operationId: atlassianAddworklog
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Add Worklog
      tags:
      - Issue Worklogs
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - write:issue-worklog:jira
        - write:issue-worklog.property:jira
        - read:avatar:jira
        - read:group:jira
        - read:issue-worklog:jira
        - read:project-role:jira
        - read:user:jira
        - read:issue-worklog.property:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/issue/{issueIdOrKey}/worklog/{id}:
    delete:
      deprecated: false
      description: Deletes a worklog from an issue.<br><br>Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-level security[...]
      operationId: atlassianDeleteworklog
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Delete Worklog
      tags:
      - Issue Worklogs
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:issue-worklog:jira
        - delete:issue-worklog.property:jira
        - write:issue.time-tracking:jira
        state: Beta
      x-atlassian-connect-scope: DELETE
    get:
      deprecated: false
      description: Returns a worklog.<br><br>Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-level security](https://conf[...]
      operationId: atlassianGetworklog
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Worklog
      tags:
      - Issue Worklogs
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:comment:jira
        - read:group:jira
        - read:issue-worklog:jira
        - read:issue-worklog.property:jira
        - read:project-role:jira
        - read:user:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Updates a worklog.<br><br>Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.<br> *  If [issue-level security](https://conf[...]
      operationId: atlassianUpdateworklog
      security:
      - basicAuth: []
      - OAuth2:
        - write:jira-work
      - {}
      summary: Atlassian Update Worklog
      tags:
      - Issue Worklogs
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - write:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:comment:jira
        - read:group:jira
        - read:issue-worklog:jira
        - read:issue-worklog.property:jira
        - read:project-role:jira
        - read:user:jira
        - write:comment:jira
        - write:issue-worklog:jira
        - write:issue-worklog.property:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: WRITE
  /rest/api/3/worklog/deleted:
    get:
      deprecated: false
      description: Returns a list of IDs and delete timestamps for worklogs deleted after a date and time.<br><br>This resource is paginated, with a limit of 1000 worklogs per page. Each page lists worklogs from oldest to youngest. If the number of items in the date range exceeds 1000, `until` indicates the timestamp of the youngest item on the page. Also, `nextPage` provides the URL for the next page of worklogs. The `lastPage` parameter is set to true on the last page of worklogs.<br><br>This [...]
      operationId: atlassianGetidsofworklogsdeletedsince
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Get Ids Of Deleted Worklogs
      tags:
      - Issue Worklogs
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-worklog:jira
        - read:issue-worklog.property:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/worklog/list:
    post:
      deprecated: false
      description: Returns worklog details for a list of worklog IDs.<br><br>The returned list of worklogs is limited to 1000 items.<br><br>**[Permissions](#permissions) required:** Permission to access Jira, however, worklogs are only returned where either of the following is true:<br><br> *  the worklog is set as *Viewable by All Users*.<br> *  the user is a member of a project role or group with permission to view the worklog.
      operationId: atlassianGetworklogsforids
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Get Worklogs
      tags:
      - Issue Worklogs
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:comment:jira
        - read:group:jira
        - read:issue-worklog:jira
        - read:issue-worklog.property:jira
        - read:project-role:jira
        - read:user:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/worklog/updated:
    get:
      deprecated: false
      description: Returns a list of IDs and update timestamps for worklogs updated after a date and time.<br><br>This resource is paginated, with a limit of 1000 worklogs per page. Each page lists worklogs from oldest to youngest. If the number of items in the date range exceeds 1000, `until` indicates the timestamp of the youngest item on the page. Also, `nextPage` provides the URL for the next page of worklogs. The `lastPage` parameter is set to true on the last page of worklogs.<br><br>This [...]
      operationId: atlassianGetidsofworklogsmodifiedsince
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Get Ids Of Updated Worklogs
      tags:
      - Issue Worklogs
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-worklog:jira
        - read:issue-worklog.property:jira
        state: Beta
      x-atlassian-connect-scope: READ
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.