openapi: 3.1.0
info:
  title: Atlassian Admin Account Content Properties API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Content Properties
paths:
  /wiki/rest/api/content/{id}/property:
    get:
      tags:
      - Content Properties
      summary: Atlassian Get Content Properties
      deprecated: true
      description: Returns the properties for a piece of content. For more information<br>about content properties, see [Confluence entity properties](https://developer.atlassian.com/cloud/confluence/confluence-entity-properties/).<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>'View' permission for the space, and permission to view the content if it is a page.
      operationId: atlassianGetcontentproperties
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
    post:
      tags:
      - Content Properties
      summary: Atlassian Create Content Property
      deprecated: true
      description: Creates a property for an existing piece of content. For more information<br>about content properties, see [Confluence entity properties](https://developer.atlassian.com/cloud/confluence/confluence-entity-properties/).<br><br>This is the same as [Create content property for key](#api-content-id-property-key-post)<br>except that the key is specified in the request body instead of as a<br>path parameter.<br><br>Content properties can also be added when creating a new piece of co[...]
      operationId: atlassianCreatecontentproperty
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content.property:confluence
        - write:content.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
  /wiki/rest/api/content/{id}/property/{key}:
    get:
      tags:
      - Content Properties
      summary: Atlassian Get Content Property
      deprecated: true
      description: Returns a content property for a piece of content. For more information, see<br>[Confluence entity properties](https://developer.atlassian.com/cloud/confluence/confluence-entity-properties/).<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>'View' permission for the space, and permission to view the content if it is a page.
      operationId: atlassianGetcontentproperty
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
    put:
      tags:
      - Content Properties
      summary: Atlassian Update Content Property
      deprecated: true
      description: Updates an existing content property. This method will also create a new<br>property for a piece of content, if the property key does not exist and<br>the property version is 1. For more information about content properties, see<br>[Confluence entity properties](https://developer.atlassian.com/cloud/confluence/confluence-entity-properties/).<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to update the content.
      operationId: atlassianUpdatecontentproperty
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content.property:confluence
        - write:content.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    post:
      tags:
      - Content Properties
      summary: Atlassian Create Content Property For Key
      deprecated: true
      description: Creates a property for an existing piece of content. For more information<br>about content properties, see [Confluence entity properties](https://developer.atlassian.com/cloud/confluence/confluence-entity-properties/).<br><br>This is the same as [Create content property](#api-content-id-property-post)<br>except that the key is specified as a path parameter instead of in the<br>request body.<br><br>Content properties can also be added when creating a new piece of content<br>by [...]
      operationId: atlassianCreatecontentpropertyforkey
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content.property:confluence
        - write:content.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    delete:
      tags:
      - Content Properties
      summary: Atlassian Delete Content Property
      deprecated: true
      description: Deletes a content property. For more information about content properties, see<br>[Confluence entity properties](https://developer.atlassian.com/cloud/confluence/confluence-entity-properties/).<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to update the content.
      operationId: atlassianDeletecontentproperty
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.