openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Fields API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Fields
paths:
  /rest/api/3/field/search:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of fields for Classic Jira projects. The list can include:<br><br> *  all fields<br> *  specific fields, by defining `id`<br> *  fields that contain a string in the field name or description, by defining `query`<br> *  specific fields that contain a string in the field name or description, by defining `id` and `query`<br><br>Only custom fields can be queried, `type` must be set to `custom`.<br><br>**[Permissions](#permissions) required:*[...]
      operationId: atlassianGetfieldspaginated
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Get Fields Paginated
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        - read:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: NONE
  /rest/api/3/field/search/trashed:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of fields in the trash. The list may be restricted to fields whose field name or description partially match a string.<br><br>Only custom fields can be queried, `type` must be set to `custom`.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGettrashedfieldspaginated
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      summary: Atlassian Get Fields In Trash Paginated
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        - read:field-configuration:jira
        - read:user:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/field/{fieldId}:
    put:
      deprecated: false
      description: Updates a custom field.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatecustomfield
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Custom Field
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{fieldId}/contexts:
    get:
      deprecated: true
      description: Returns a [paginated](#pagination) list of the contexts a field is used in. Deprecated, use [ Get custom field contexts](#api-rest-api-3-field-fieldId-context-get).<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetcontextsforfielddeprecated
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      - {}
      summary: Atlassian Get Contexts For A Field
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        - read:avatar:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: NONE
  /rest/api/3/field/{id}:
    delete:
      deprecated: false
      description: Deletes a custom field. The custom field is deleted whether it is in the trash or not. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.<br><br>This operation is [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.<br><br>**[Permissions](#permissions) require[...]
      operationId: atlassianDeletecustomfield
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Custom Field
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{id}/restore:
    post:
      deprecated: false
      description: Restores a custom field from trash. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianRestorecustomfield
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Restore Custom Field From Trash
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field/{id}/trash:
    post:
      deprecated: false
      description: Moves a custom field to trash. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianTrashcustomfield
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Move Custom Field To Trash
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:field:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/field:
    get:
      deprecated: false
      description: Returns system and custom issue fields according to the following rules:<br><br> *  Fields that cannot be added to the issue navigator are always returned.<br> *  Fields that cannot be placed on an issue screen are always returned.<br> *  Fields that depend on global Jira settings are only returned if the setting is enabled. That is, timetracking fields, subtasks, votes, and watches.<br> *  For all other fields, this operation only returns the fields that the user has permissi[...]
      operationId: atlassianGetfields
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Fields
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        - read:avatar:jira
        - read:project-category:jira
        - read:project:jira
        - read:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Creates a custom field.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreatecustomfield
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      - {}
      summary: Atlassian Create Custom Field
      tags:
      - Issue Fields
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field:jira
        - read:avatar:jira
        - read:field:jira
        - read:project-category:jira
        - read:project:jira
        - read:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.