openapi: 3.1.0
info:
  title: Atlassian Admin Account Space Properties API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Space Properties
paths:
  /wiki/rest/api/space/{spaceKey}/property:
    get:
      tags:
      - Space Properties
      summary: Atlassian Get Space Properties
      deprecated: true
      description: 'Deprecated, use [Confluence''s v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).<br><br>Returns all properties for the given space. Space properties are a key-value storage associated with a space.<br><br>**[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘View’ permission for the space.'
      operationId: atlassianGetspaceproperties
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      tags:
      - Space Properties
      summary: Atlassian Create Space Property
      deprecated: true
      description: Deprecated, use [Confluence's v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).<br><br>Creates a new space property.<br><br>**[Permissions required](https://confluence.atlassian.com/x/_AozKw)**:<br>‘Admin’ permission for the space.
      operationId: atlassianCreatespaceproperty
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:space.property:confluence
        - write:space.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/space/{spaceKey}/property/{key}:
    get:
      tags:
      - Space Properties
      summary: Atlassian Get Space Property
      deprecated: true
      description: 'Deprecated, use [Confluence''s v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).<br><br>Returns a space property.<br><br>**[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘View’ permission for the space.'
      operationId: atlassianGetspaceproperty
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      tags:
      - Space Properties
      summary: Atlassian Update Space Property
      deprecated: true
      description: Deprecated, use [Confluence's v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).<br><br>Updates a space property. Note, you cannot update the key of a space<br>property, only the value.<br><br>**[Permissions required](https://confluence.atlassian.com/x/_AozKw)**:<br>‘Admin’ permission for the space.
      operationId: atlassianUpdatespaceproperty
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:space.property:confluence
        - write:space.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      tags:
      - Space Properties
      summary: Atlassian Create Space Property for Key
      deprecated: true
      description: Deprecated, use [Confluence's v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).<br><br>Creates a new space property. This is the same as `POST<br>/wiki/rest/api/space/{spaceKey}/property` but the key for the property is passed as a<br>path parameter, rather than in the request body.<br><br>**[Permissions required](https://confluence.atlassian.com/x/_AozKw)**:<br>‘Admin’ permission for the space.
      operationId: atlassianCreatespacepropertyforkey
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:space.property:confluence
        - write:space.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Space Properties
      summary: Atlassian Delete Space Property
      deprecated: true
      description: Deprecated, use [Confluence's v2 API](https://developer.atlassian.com/cloud/confluence/rest/v2/intro/).<br><br>Deletes a space property.<br><br>**[Permissions required](https://confluence.atlassian.com/x/_AozKw)**:<br>‘Admin’ permission for the space.
      operationId: atlassianDeletespaceproperty
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-props
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-props
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:space.property:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.