openapi: 3.1.0
info:
  title: Atlassian Admin Account JQL API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: JQL
paths:
  /rest/api/3/jql/autocompletedata:
    get:
      deprecated: false
      description: Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.<br><br>To filter visib[...]
      operationId: atlassianGetautocomplete
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Field Reference Data Get
      tags:
      - JQL
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        state: Beta
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Returns reference data for JQL searches. This is a downloadable version of the documentation provided in [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ) and [Advanced searching - functions reference](https://confluence.atlassian.com/x/hgORLQ), along with a list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the validation of queries built in a custom query builder.<br><br>This operation [...]
      operationId: atlassianGetautocompletepost
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Field Reference Data Post
      tags:
      - JQL
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/jql/autocompletedata/suggestions:
    get:
      deprecated: false
      description: Returns the JQL search auto complete suggestions for a field.<br><br>Suggestions can be obtained by providing:<br><br> *  `fieldName` to get a list of all values for the field.<br> *  `fieldName` and `fieldValue` to get a list of values containing the text in `fieldValue`.<br> *  `fieldName` and `predicateName` to get a list of all predicate values for the field.<br> *  `fieldName`, `predicateName`, and `predicateValue` to get a list of predicate values containing the text in [...]
      operationId: atlassianGetfieldautocompleteforquerystring
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Field Auto Complete Suggestions
      tags:
      - JQL
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:issue-details:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/jql/parse:
    post:
      deprecated: false
      description: Parses and validates JQL queries.<br><br>Validation is performed in context of the current user.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** None.
      operationId: atlassianParsejqlqueries
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Parse Jql Query
      tags:
      - JQL
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field:jira
        - validate:jql:jira
        - read:jql:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: READ
  /rest/api/3/jql/pdcleaner:
    post:
      deprecated: false
      description: Converts one or more JQL queries with user identifiers (username or user key) to equivalent JQL queries with account IDs.<br><br>You may wish to use this operation if your system stores JQL queries and you want to make them GDPR-compliant. For more information about GDPR-related changes, see the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).<br><br>**[Permissions](#permissions) required:** Permission[...]
      operationId: atlassianMigratequeries
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      summary: Atlassian Convert User Identifiers To Account Ids In Jql Queries
      tags:
      - JQL
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user:jira
        - read:jql:jira
        - validate:jql:jira
        state: Beta
      x-atlassian-connect-scope: READ
  /rest/api/3/jql/sanitize:
    post:
      deprecated: false
      description: Sanitizes one or more JQL queries by converting readable details into IDs where a user doesn't have permission to view the entity.<br><br>For example, if the query contains the clause *project = 'Secret project'*, and a user does not have browse permission for the project "Secret project", the sanitized query replaces the clause with *project = 12345"* (where 12345 is the ID of the project). If a user has the required permission, the clause is not sanitized. If the account ID [...]
      operationId: atlassianSanitisejqlqueries
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Sanitize Jql Queries
      tags:
      - JQL
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:jql:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.