openapi: 3.1.0
info:
  title: Atlassian Admin Account Content Restrictions API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Content Restrictions
paths:
  /wiki/rest/api/content/{id}/restriction:
    get:
      tags:
      - Content Restrictions
      summary: Atlassian Get Restrictions
      description: Returns the restrictions on a piece of content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to view the content.
      operationId: atlassianGetrestrictions
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.all
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.all
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
    put:
      tags:
      - Content Restrictions
      summary: Atlassian Update Restrictions
      description: 'Updates restrictions for a piece of content. For each operation specified in the request, it removes<br>any existing restrictions on the content for that operation, and replaces them with the restrictions in the request.<br>Note: Not specifying an operation will ignore restrictions of that type, and passing an empty list for an operation<br>will remove all existing restrictions of that type.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Perm[...]'
      operationId: atlassianUpdaterestrictions
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    post:
      tags:
      - Content Restrictions
      summary: Atlassian Add Restrictions
      description: Adds restrictions to a piece of content. Note, this does not change any<br>existing restrictions on the content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianAddrestrictions
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    delete:
      tags:
      - Content Restrictions
      summary: Atlassian Delete Restrictions
      description: Removes all restrictions (read and update) on a piece of content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianDeleterestrictions
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: DELETE
  /wiki/rest/api/content/{id}/restriction/byOperation:
    get:
      tags:
      - Content Restrictions
      summary: Atlassian Get Restrictions By Operation
      description: Returns restrictions on a piece of content by operation. This method is<br>similar to [Get restrictions](#api-content-id-restriction-get) except that<br>the operations are properties of the return object, rather than items in<br>a results array.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to view the content.
      operationId: atlassianGetrestrictionsbyoperation
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.all
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.all
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
  /wiki/rest/api/content/{id}/restriction/byOperation/{operationKey}:
    get:
      tags:
      - Content Restrictions
      summary: Atlassian Get Restrictions For Operation
      description: Returns the restictions on a piece of content for a given operation (read<br>or update).<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to view the content.
      operationId: atlassianGetrestrictionsforoperation
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.all
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.all
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content-details:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
  /wiki/rest/api/content/{id}/restriction/byOperation/{operationKey}/group/{groupName}:
    get:
      tags:
      - Content Restrictions
      summary: Atlassian Get Content Restriction Status For Group
      deprecated: true
      description: Deprecated, use [Get content restriction status for group via groupId](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-content-restrictions/#api-wiki-rest-api-content-id-restriction-byoperation-operationkey-bygroupid-groupid-get).<br>Returns whether the specified content restriction applies to a group.<br>For example, if a page with `id=123` has a `read` restriction for the `admins` group,<br>the following request will return `true`:<br><br>`/wiki/rest/api/c[...]
      operationId: atlassianGetcontentrestrictionstatusforgroup
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.all
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.all
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
    put:
      tags:
      - Content Restrictions
      summary: Atlassian Add Group To Content Restriction
      deprecated: true
      description: Deprecated, use [Add group to content restriction via groupId](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-content-restrictions/#api-wiki-rest-api-content-id-restriction-byoperation-operationkey-bygroupid-groupid-put).<br>Adds a group to a content restriction. That is, grant read or update<br>permission to the group for a piece of content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianAddgrouptocontentrestriction
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    delete:
      tags:
      - Content Restrictions
      summary: Atlassian Remove Group From Content Restriction
      deprecated: true
      description: Deprecated, use [Remove group from content restriction by groupId](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-content-restrictions/#api-wiki-rest-api-content-id-restriction-byoperation-operationkey-user-delete).<br>Removes a group from a content restriction. That is, remove read or update<br>permission for the group for a piece of content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianRemovegroupfromcontentrestrictionbyid
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
  /wiki/rest/api/content/{id}/restriction/byOperation/{operationKey}/byGroupId/{groupId}:
    get:
      tags:
      - Content Restrictions
      summary: Atlassian Get Content Restriction Status For Group
      description: Returns whether the specified content restriction applies to a group.<br>For example, if a page with `id=123` has a `read` restriction for the `123456` group id,<br>the following request will return `true`:<br><br>`/wiki/rest/api/content/123/restriction/byOperation/read/byGroupId/123456`<br><br>Note that a response of `true` does not guarantee that the group can view the page, as it does not account for<br>account-inherited restrictions, space permissions, or even product acce[...]
      operationId: atlassianGetindividualgrouprestrictionstatusbygroupid
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.all
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.all
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
    put:
      tags:
      - Content Restrictions
      summary: Atlassian Add Group To Content Restriction
      description: Adds a group to a content restriction by Group Id. That is, grant read or update<br>permission to the group for a piece of content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianAddgrouptocontentrestrictionbygroupid
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    delete:
      tags:
      - Content Restrictions
      summary: Atlassian Remove Group From Content Restriction
      description: Removes a group from a content restriction. That is, remove read or update<br>permission for the group for a piece of content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianRemovegroupfromcontentrestriction
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
  /wiki/rest/api/content/{id}/restriction/byOperation/{operationKey}/user:
    get:
      tags:
      - Content Restrictions
      summary: Atlassian Get Content Restriction Status For User
      description: Returns whether the specified content restriction applies to a user.<br>For example, if a page with `id=123` has a `read` restriction for a user with an account ID of<br>`384093:32b4d9w0-f6a5-3535-11a3-9c8c88d10192`, the following request will return `true`:<br><br>`/wiki/rest/api/content/123/restriction/byOperation/read/user?accountId=384093:32b4d9w0-f6a5-3535-11a3-9c8c88d10192`<br><br>Note that a response of `true` does not guarantee that the user can view the page, as it do[...]
      operationId: atlassianGetcontentrestrictionstatusforuser
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.all
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.all
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
    put:
      tags:
      - Content Restrictions
      summary: Atlassian Add User To Content Restriction
      description: Adds a user to a content restriction. That is, grant read or update<br>permission to the user for a piece of content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianAddusertocontentrestriction
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
    delete:
      tags:
      - Content Restrictions
      summary: Atlassian Remove User From Content Restriction
      description: Removes a group from a content restriction. That is, remove read or update<br>permission for the group for a piece of content.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>Permission to edit the content.
      operationId: atlassianRemoveuserfromcontentrestriction
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:content.restriction:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.