openapi: 3.1.0
info:
  title: Atlassian Admin Account Workflows API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Workflows
paths:
  /rest/api/3/workflow/search:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of published classic workflows. When workflow names are specified, details of those workflows are returned. Otherwise, all published classic workflows are returned.<br><br>This operation does not return next-gen workflows.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetworkflowspaginated
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-project
      summary: Atlassian Get Workflows Paginated
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-project
        state: Current
      - scheme: OAuth2
        scopes:
        - read:group:jira
        - read:issue-security-level:jira
        - read:project-role:jira
        - read:screen:jira
        - read:status:jira
        - read:user:jira
        - read:workflow:jira
        - read:webhook:jira
        - read:avatar:jira
        - read:project-category:jira
        - read:project:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflow/{entityId}:
    delete:
      deprecated: false
      description: Deletes a workflow.<br><br>The workflow cannot be deleted if it is:<br><br> *  an active workflow.<br> *  a system workflow.<br> *  associated with any workflow scheme.<br> *  associated with any draft workflow scheme.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeleteinactiveworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Inactive Workflow
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:workflow:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflows/capabilities:
    get:
      deprecated: false
      description: 'Get the list of workflow capabilities for a specific workflow using either the workflow ID, or the project and issue type ID pair. The response includes the scope of the workflow, defined as global/project-based, and a list of project types that the workflow is scoped to. It also includes all rules organised into their broad categories (conditions, validators, actions, triggers, screens) as well as the source location (Atlassian-provided, Connect, Forge).<br><br>**[Permission[...]'
      operationId: atlassianWorkflowcapabilities
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Available Workflow Capabilities
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflows/create:
    post:
      deprecated: false
      description: Create workflows and related statuses.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* project permission to create all, including global-scoped, workflows<br> *  *Administer projects* project permissions to create project-scoped workflows
      operationId: atlassianCreateworkflows
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Bulk Create Workflows
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflows/create/validation:
    post:
      deprecated: false
      description: Validate the payload for bulk create workflows.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* project permission to create all, including global-scoped, workflows<br> *  *Administer projects* project permissions to create project-scoped workflows
      operationId: atlassianValidatecreateworkflows
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Validate Create Workflows
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflows/update:
    post:
      deprecated: false
      description: Update workflows and related statuses.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* project permission to create all, including global-scoped, workflows<br> *  *Administer projects* project permissions to create project-scoped workflows
      operationId: atlassianUpdateworkflows
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Bulk Update Workflows
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflows/update/validation:
    post:
      deprecated: false
      description: Validate the payload for bulk update workflows.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* project permission to create all, including global-scoped, workflows<br> *  *Administer projects* project permissions to create project-scoped workflows
      operationId: atlassianValidateupdateworkflows
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Validate Update Workflows
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflow:
    get:
      deprecated: true
      description: Returns all workflows in Jira or a workflow. Deprecated, use [Get workflows paginated](#api-rest-api-3-workflow-search-get).<br><br>If the `workflowName` parameter is specified, the workflow is returned as an object (not in an array). Otherwise, an array of workflow objects is returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetallworkflows
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get All Workflows
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow:jira
        - read:project:jira
        - read:project-category:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    post:
      deprecated: true
      description: 'Creates a workflow. You can define transition rules using the shapes detailed in the following sections. If no transitional rules are specified the default system transition rules are used. Note: This only applies to company-managed scoped workflows. Use [bulk create workflows](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflows/#api-rest-api-3-workflows-create-post) to create both team and company-managed scoped workflows.<br><br>#### Conditions #[...]'
      operationId: atlassianCreateworkflow
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Workflow
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:workflow:jira
        - read:workflow:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/workflows:
    post:
      deprecated: false
      description: Returns a list of workflows and related statuses by providing workflow names, workflow IDs, or project and issue types.<br><br>**[Permissions](#permissions) required:**<br><br> *  *Administer Jira* global permission to access all, including project-scoped, workflows<br> *  At least one of the *Administer projects* and *View (read-only) workflow* project permissions to access project-scoped workflows
      operationId: atlassianReadworkflows
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Bulk Get Workflows
      tags:
      - Workflows
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:workflow:jira
        state: Beta
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.