openapi: 3.1.0
info:
  title: Atlassian Admin Account Content Watches API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Content Watches
paths:
  /wiki/rest/api/space/{spaceKey}/watch:
    get:
      tags:
      - Content Watches
      summary: Atlassian Get Space Watchers
      description: Returns a list of watchers of a space
      operationId: atlassianGetwatchersforspace
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:watcher:confluence
        - read:user:confluence
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:watcher:confluence
        - read:user:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/user/watch/content/{contentId}:
    get:
      tags:
      - Content Watches
      summary: Atlassian Get Content Watch Status
      description: 'Returns whether a user is watching a piece of content. Choose the user by<br>doing one of the following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Confluence Administrator'' global permission if specifying a user, otherwise<br>permission to access the Confluence site (''Can use'[...]'
      operationId: atlassianGetcontentwatchstatus
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      tags:
      - Content Watches
      summary: Atlassian Add Content Watcher
      description: 'Adds a user as a watcher to a piece of content. Choose the user by doing<br>one of the following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>Note, you must add the `X-Atlassian-Token: no-check` header when making a<br>request, as this operation has XSRF protection.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Conflue[...]'
      operationId: atlassianAddcontentwatcher
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Content Watches
      summary: Atlassian Remove Content Watcher
      description: 'Removes a user as a watcher from a piece of content. Choose the user by<br>doing one of the following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Confluence Administrator'' global permission if specifying a user, otherwise<br>permission to access the Confluence site (''Can use'' [...]'
      operationId: atlassianRemovecontentwatcher
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/user/watch/label/{labelName}:
    get:
      tags:
      - Content Watches
      summary: Atlassian Get Label Watch Status
      description: 'Returns whether a user is watching a label. Choose the user by doing one<br>of the following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Confluence Administrator'' global permission if specifying a user, otherwise<br>permission to access the Confluence site (''Can use'' global pe[...]'
      operationId: atlassianIswatchinglabel
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      tags:
      - Content Watches
      summary: Atlassian Add Label Watcher
      description: 'Adds a user as a watcher to a label. Choose the user by doing one of the<br>following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>Note, you must add the `X-Atlassian-Token: no-check` header when making a<br>request, as this operation has XSRF protection.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Confluence Adminis[...]'
      operationId: atlassianAddlabelwatcher
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Content Watches
      summary: Atlassian Remove Label Watcher
      description: 'Removes a user as a watcher from a label. Choose the user by doing one of<br>the following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Confluence Administrator'' global permission if specifying a user, otherwise<br>permission to access the Confluence site (''Can use'' global perm[...]'
      operationId: atlassianRemovelabelwatcher
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/user/watch/space/{spaceKey}:
    get:
      tags:
      - Content Watches
      summary: Atlassian Get Space Watch Status
      description: 'Returns whether a user is watching a space. Choose the user by<br>doing one of the following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Confluence Administrator'' global permission if specifying a user, otherwise<br>permission to access the Confluence site (''Can use'' global pe[...]'
      operationId: atlassianIswatchingspace
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      tags:
      - Content Watches
      summary: Atlassian Add Space Watcher
      description: 'Adds a user as a watcher to a space. Choose the user by doing one of the<br>following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>Note, you must add the `X-Atlassian-Token: no-check` header when making a<br>request, as this operation has XSRF protection.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Confluence Adminis[...]'
      operationId: atlassianAddspacewatcher
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Content Watches
      summary: Atlassian Remove Space Watch
      description: 'Removes a user as a watcher from a space. Choose the user by doing one of<br>the following:<br><br>- Specify a user via a query parameter: Use the `accountId` to identify the user.<br>- Do not specify a user: The currently logged-in user will be used.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>''Confluence Administrator'' global permission if specifying a user, otherwise<br>permission to access the Confluence site (''Can use'' global perm[...]'
      operationId: atlassianRemovespacewatch
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-content
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-content
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:watcher:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/content/{id}/notification/child-created:
    get:
      tags:
      - Content Watches
      summary: Atlassian Get Watches For Page
      description: Returns the watches for a page. A user that watches a page will receive<br>receive notifications when the page is updated.<br><br>If you want to manage watches for a page, use the following `user` methods:<br><br>- [Get content watch status for user](#api-user-watch-content-contentId-get)<br>- [Add content watch](#api-user-watch-content-contentId-post)<br>- [Remove content watch](#api-user-watch-content-contentId-delete)<br><br>**[Permissions](https://confluence.atlassian.com/[...]
      operationId: atlassianGetwatchesforpage
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:watcher:confluence
        - read:user:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: false
      x-atlassian-connect-scope: READ
  /wiki/rest/api/content/{id}/notification/created:
    get:
      tags:
      - Content Watches
      summary: Atlassian Get Watches For Space
      description: Returns all space watches for the space that the content is in. A user that<br>watches a space will receive receive notifications when any content in the<br>space is updated.<br><br>If you want to manage watches for a space, use the following `user` methods:<br><br>- [Get space watch status for user](#api-user-watch-space-spaceKey-get)<br>- [Add space watch](#api-user-watch-space-spaceKey-post)<br>- [Remove space watch](#api-user-watch-space-spaceKey-delete)<br><br>**[Permissi[...]
      operationId: atlassianGetwatchesforspace
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-content.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-content.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:watcher:confluence
        - read:user:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.