openapi: 3.1.0
info:
  title: Atlassian Admin Account Pullrequests API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Pullrequests
paths:
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/tasks/{task_id}:
    put:
      tags:
      - Pullrequests
      description: This API operation updates an existing task associated with a specific pull request in a Bitbucket repository. By sending a PUT request to the endpoint with the workspace identifier, repository slug, pull request ID, and task ID, you can modify task properties such as its content, state, or other metadata. This is useful for managing and tracking action items or to-do items that are linked to code reviews within pull requests, allowing teams to update task status or details as[...]
      summary: Atlassian Update Task on Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: updateTaskOnPullRequest
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Pullrequests
      description: Deletes a specific pull request task.
      summary: Atlassian Delete A Task On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianDeleteATaskOnAPullRequest
    get:
      tags:
      - Pullrequests
      description: Returns a specific pull request task.
      summary: Atlassian Get A Task On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetATaskOnAPullRequest
  /pullrequests/{selected_user}:
    get:
      tags:
      - Pullrequests
      description: Returns all pull requests authored by the specified user.<br><br>By default only open pull requests are returned. This can be controlled<br>using the `state` query parameter. To retrieve pull requests that are<br>in one of multiple states, repeat the `state` parameter for each<br>individual state.<br><br>This endpoint also supports filtering and sorting of the results. See<br>[filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more details.
      summary: Atlassian List Pull Requests For A User
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      operationId: atlassianListPullRequestsForAUser
  /repositories/{workspace}/{repo_slug}/pullrequests:
    get:
      tags:
      - Pullrequests
      description: Returns all pull requests on the specified repository.<br><br>By default only open pull requests are returned. This can be controlled<br>using the `state` query parameter. To retrieve pull requests that are<br>in one of multiple states, repeat the `state` parameter for each<br>individual state.<br><br>This endpoint also supports filtering and sorting of the results. See<br>[filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more details.
      summary: Atlassian List Pull Requests
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListPullRequests
    post:
      tags:
      - Pullrequests
      description: 'Creates a new pull request where the destination repository is<br>this repository and the author is the authenticated user.<br><br>The minimum required fields to create a pull request are `title` and<br>`source`, specified by a branch name.<br><br>```<br>curl https://api.bitbucket.org/2.0/repositories/my-workspace/my-repository/pullrequests \<br>    -u my-username:my-password \<br>    --request POST \<br>    --header ''Content-Type: application/json'' \<br>    --data ''{<br> [...]'
      summary: Atlassian Create A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianCreateAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/activity:
    get:
      tags:
      - Pullrequests
      description: 'Returns a paginated list of the pull request''s activity log.<br><br>This handler serves both a v20 and internal endpoint. The v20 endpoint<br>returns reviewer comments, updates, approvals and request changes. The internal<br>endpoint includes those plus tasks and attachments.<br><br>Comments created on a file or a line of code have an inline property.<br><br>Comment example:<br>```<br>{<br>    "pagelen": 20,<br>    "values": [<br>        {<br>            "comment": {<br>    [...]'
      summary: Atlassian List A Pull Request Activity Log
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListAPullRequestActivityLog
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}:
    get:
      tags:
      - Pullrequests
      description: Returns the specified pull request.
      summary: Atlassian Get A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetAPullRequest
    put:
      tags:
      - Pullrequests
      description: Mutates the specified pull request.<br><br>This can be used to change the pull request's branches or description.<br><br>Only open pull requests can be mutated.
      summary: Atlassian Update A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianUpdateAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/activity:
    get:
      tags:
      - Pullrequests
      description: 'Returns a paginated list of the pull request''s activity log.<br><br>This handler serves both a v20 and internal endpoint. The v20 endpoint<br>returns reviewer comments, updates, approvals and request changes. The internal<br>endpoint includes those plus tasks and attachments.<br><br>Comments created on a file or a line of code have an inline property.<br><br>Comment example:<br>```<br>{<br>    "pagelen": 20,<br>    "values": [<br>        {<br>            "comment": {<br>    [...]'
      summary: Atlassian List A Pull Request Activity Log
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListAPullRequestActivityLog
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve:
    delete:
      tags:
      - Pullrequests
      description: Redact the authenticated user's approval of the specified pull<br>request.
      summary: Atlassian Unapprove A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - write:pullrequest:bitbucket
      operationId: atlassianUnapproveAPullRequest
    post:
      tags:
      - Pullrequests
      description: Approve the specified pull request as the authenticated user.
      summary: Atlassian Approve A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianApproveAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments:
    get:
      tags:
      - Pullrequests
      description: Returns a paginated list of the pull request's comments.<br><br>This includes both global, inline comments and replies.<br><br>The default sorting is oldest to newest and can be overridden with<br>the `sort` query parameter.<br><br>This endpoint also supports filtering and sorting of the results. See<br>[filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more<br>details.
      summary: Atlassian List Comments On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListCommentsOnAPullRequest
    post:
      tags:
      - Pullrequests
      description: Creates a new pull request comment.<br><br>Returns the newly created pull request comment.
      summary: Atlassian Create A Comment On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianCreateACommentOnAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}:
    delete:
      tags:
      - Pullrequests
      description: Deletes a specific pull request comment.
      summary: Atlassian Delete A Comment On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianDeleteACommentOnAPullRequest
    get:
      tags:
      - Pullrequests
      description: Returns a specific pull request comment.
      summary: Atlassian Get A Comment On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetACommentOnAPullRequest
    put:
      tags:
      - Pullrequests
      description: Updates a specific pull request comment.
      summary: Atlassian Update A Comment On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianUpdateACommentOnAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}/resolve:
    delete:
      tags:
      - Pullrequests
      description: Needs a more full description created.
      summary: Atlassian Reopen A Comment Thread
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianReopenACommentThread
    post:
      tags:
      - Pullrequests
      description: Needs a more full description created.
      summary: Atlassian Resolve A Comment Thread
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianResolveACommentThread
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/commits:
    get:
      tags:
      - Pullrequests
      description: Returns a paginated list of the pull request's commits.<br><br>These are the commits that are being merged into the destination<br>branch when the pull requests gets accepted.
      summary: Atlassian List Commits On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListCommitsOnAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/decline:
    post:
      tags:
      - Pullrequests
      description: Declines the pull request.
      summary: Atlassian Decline A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianDeclineAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diff:
    get:
      tags:
      - Pullrequests
      description: Redirects to the [repository diff](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-diff-spec-get)<br>with the revspec that corresponds to the pull request.
      summary: Atlassian List Changes In A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListChangesInAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diffstat:
    get:
      tags:
      - Pullrequests
      description: Redirects to the [repository diffstat](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-diffstat-spec-get)<br>with the revspec that corresponds to the pull request.
      summary: Atlassian Get The Diff Stat For A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetTheDiffStatForAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge:
    post:
      tags:
      - Pullrequests
      description: Merges the pull request.
      summary: Atlassian Merge A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianMergeAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge/task-status/{task_id}:
    get:
      tags:
      - Pullrequests
      description: 'When merging a pull request takes too long, the client receives a<br>task ID along with a 202 status code. The task ID can be used in a call<br>to this endpoint to check the status of a merge task.<br><br>```<br>curl -X GET https://api.bitbucket.org/2.0/repositories/atlassian/bitbucket/pullrequests/2286/merge/task-status/<br>```<br><br>If the merge task is not yet finished, a PENDING status will be returned.<br><br>```<br>HTTP/2 200<br>{<br>    "task_status": "PENDING",<br>  [...]'
      summary: Atlassian Get The Merge Task Status For A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetTheMergeTaskStatusForAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/patch:
    get:
      tags:
      - Pullrequests
      description: Redirects to the [repository patch](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-patch-spec-get)<br>with the revspec that corresponds to pull request.
      summary: Atlassian Get The Patch For A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetThePatchForAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/request-changes:
    delete:
      tags:
      - Pullrequests
      description: Needs a more full description created.
      summary: Atlassian Remove Change Request For A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - write:pullrequest:bitbucket
      operationId: atlassianRemoveChangeRequestForAPullRequest
    post:
      tags:
      - Pullrequests
      description: Needs a more full description created.
      summary: Atlassian Request Changes For A Pull Request
      security:
      - oauth2:
        - pullrequest:write
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
        - write:pullrequest:bitbucket
      operationId: atlassianRequestChangesForAPullRequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/tasks:
    get:
      tags:
      - Pullrequests
      description: Returns a paginated list of the pull request's tasks.<br><br>This endpoint supports filtering and sorting of the results by the 'task' field.<br>See [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more details.
      summary: Atlassian List Tasks On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListTasksOnAPullRequest
    post:
      tags:
      - Pullrequests
      description: Creates a new pull request task.<br><br>Returns the newly created pull request task.<br><br>Tasks can optionally be created in relation to a comment specified by the comment's ID which<br>will cause the task to appear below the comment on a pull request when viewed in Bitbucket.
      summary: Atlassian Create A Task On A Pull Request
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianCreateATaskOnAPullRequest
  /repositories/{workspace}/{repo_slug}/commit/{commit}/pullrequests:
    get:
      tags:
      - Pullrequests
      summary: Atlassian List Pull Requests That Contain A Commit
      description: Returns a paginated list of all pull requests as part of which this commit was reviewed. Pull Request Commit Links app must be installed first before using this API; installation automatically occurs when 'Go to pull request' is clicked from the web interface for a commit's details.
      operationId: atlassianGetpullrequestsforcommit
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
  /repositories/{workspace}/{repo_slug}/default-reviewers:
    get:
      tags:
      - Pullrequests
      description: Returns the repository's default reviewers.<br><br>These are the users that are automatically added as reviewers on every<br>new pull request that is created. To obtain the repository's default reviewers<br>as well as the default reviewers inherited from the project, use the<br>[effective-default-reveiwers](#api-repositories-workspace-repo-slug-effective-default-reviewers-get) endpoint.
      summary: Atlassian List Default Reviewers
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListDefaultReviewers
  /repositories/{workspace}/{repo_slug}/default-reviewers/{target_username}:
    delete:
      tags:
      - Pullrequests
      description: Removes a default reviewer from the repository.
      summary: Atlassian Remove A User From The Default Reviewers
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - admin:repository:bitbucket
      operationId: atlassianRemoveAUserFromTheDefaultReviewers
    get:
      tags:
      - Pullrequests
      description: Returns the specified reviewer.<br><br>This can be used to test whether a user is among the repository's<br>default reviewers list. A 404 indicates that that specified user is not<br>a default reviewer.
      summary: Atlassian Get A Default Reviewer
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianGetADefaultReviewer
    put:
      tags:
      - Pullrequests
      description: Adds the specified user to the repository's list of default<br>reviewers.<br><br>This method is idempotent. Adding a user a second time has no effect.
      summary: Atlassian Add A User To The Default Reviewers
      security:
      - oauth2:
        - repository:admin
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - admin:repository:bitbucket
      operationId: atlassianAddAUserToTheDefaultReviewers
  /repositories/{workspace}/{repo_slug}/effective-default-reviewers:
    get:
      tags:
      - Pullrequests
      description: Returns the repository's effective default reviewers. This includes both default<br>reviewers defined at the repository level as well as those inherited from its project.<br><br>These are the users that are automatically added as reviewers on every<br>new pull request that is created.
      summary: Atlassian List Effective Default Reviewers
      security:
      - oauth2:
        - pullrequest
      - basic: []
      - api_key: []
      x-atlassian-oauth2-scopes:
      - state: Current
        scheme: oauth2
        scopes:
        - read:pullrequest:bitbucket
      operationId: atlassianListEffectiveDefaultReviewers
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.