openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Priorities API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Priorities
paths:
  /rest/api/3/priority/default:
    put:
      deprecated: false
      description: Sets default issue priority.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianSetdefaultpriority
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Set Default Priority
      tags:
      - Issue Priorities
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/priority/move:
    put:
      deprecated: false
      description: Changes the order of issue priorities.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianMovepriorities
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Move Priorities
      tags:
      - Issue Priorities
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/priority/search:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of priorities. The list can contain all priorities or a subset determined by any combination of these criteria:<br><br> *  a list of priority IDs. Any invalid priority IDs are ignored.<br> *  a list of project IDs. Only priorities that are available in these projects will be returned. Any invalid project IDs are ignored.<br> *  whether the field configuration is a default. This returns priorities from company-managed (classic) projects o[...]
      operationId: atlassianSearchpriorities
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Search Priorities
      tags:
      - Issue Priorities
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: READ
  /rest/api/3/priority/{id}:
    delete:
      deprecated: true
      description: '*Deprecated: please refer to the* [changelog](https://developer.atlassian.com/changelog/#CHANGE-1066) *for more details.*<br><br>Deletes an issue priority.<br><br>This operation is [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassia[...]'
      operationId: atlassianDeletepriority
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Priority
      tags:
      - Issue Priorities
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-changes:
      - announced: '2023-07-18'
        details: https://developer.atlassian.com/changelog/#CHANGE-1066
        effective: '2023-12-01'
        type: removed
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
    get:
      deprecated: false
      description: Returns an issue priority.<br><br>**[Permissions](#permissions) required:** Permission to access Jira.
      operationId: atlassianGetpriority
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Priority
      tags:
      - Issue Priorities
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:priority:jira
        state: Beta
      x-atlassian-connect-scope: READ
    put:
      deprecated: false
      description: Updates an issue priority.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatepriority
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Priority
      tags:
      - Issue Priorities
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/priority:
    get:
      deprecated: true
      description: Returns the list of all issue priorities.<br><br>**[Permissions](#permissions) required:** Permission to access Jira.
      operationId: atlassianGetpriorities
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-work
      - {}
      summary: Atlassian Get Priorities
      tags:
      - Issue Priorities
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-work
        state: Current
      - scheme: OAuth2
        scopes:
        - read:priority:jira
        state: Beta
      x-changes:
      - announced: '2022-10-11'
        details: https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-762
        effective: '2023-04-11'
        type: removed
      x-atlassian-connect-scope: READ
    post:
      deprecated: false
      description: Creates an issue priority.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreatepriority
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Priority
      tags:
      - Issue Priorities
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-experimental: true
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.