openapi: 3.1.0
info:
  title: Atlassian Admin Account Themes API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Themes
paths:
  /wiki/rest/api/settings/theme:
    get:
      tags:
      - Themes
      summary: Atlassian Get Themes
      description: 'Returns all themes, not including the default theme.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: None'
      operationId: atlassianGetthemes
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - manage:confluence-configuration
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - manage:confluence-configuration
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:configuration:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/settings/theme/selected:
    get:
      tags:
      - Themes
      summary: Atlassian Get Global Theme
      description: 'Returns the globally assigned theme.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: None'
      operationId: atlassianGetglobaltheme
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - manage:confluence-configuration
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - manage:confluence-configuration
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:configuration:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/settings/theme/{themeKey}:
    get:
      tags:
      - Themes
      summary: Atlassian Get Theme
      description: 'Returns a theme. This includes information about the theme name,<br>description, and icon.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: None'
      operationId: atlassianGettheme
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - manage:confluence-configuration
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - manage:confluence-configuration
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:configuration:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /wiki/rest/api/space/{spaceKey}/theme:
    get:
      tags:
      - Themes
      summary: Atlassian Get Space Theme
      description: 'Returns the theme selected for a space, if one is set. If no space<br>theme is set, this means that the space is inheriting the global look<br>and feel settings.<br><br>**[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘View’ permission for the space.'
      operationId: atlassianGetspacetheme
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - read:confluence-space.summary
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - read:confluence-space.summary
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:space.setting:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: READ
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      tags:
      - Themes
      summary: Atlassian Set Space Theme
      description: Sets the theme for a space. Note, if you want to reset the space theme to<br>the default Confluence theme, use the 'Reset space theme' method instead<br>of this method.<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>'Admin' permission for the space.
      operationId: atlassianSetspacetheme
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-space
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-space
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - read:space.setting:confluence
        - write:space.setting:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: WRITE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Themes
      summary: Atlassian Reset Space Theme
      description: Resets the space theme. This means that the space will inherit the<br>global look and feel settings<br><br>**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:<br>'Admin' permission for the space.
      operationId: atlassianResetspacetheme
      security:
      - basicAuth: []
      - oAuthDefinitions:
        - write:confluence-space
      x-atlassian-oauth2-scopes:
      - scheme: oAuthDefinitions
        state: Current
        scopes:
        - write:confluence-space
      - scheme: oAuthDefinitions
        state: Beta
        scopes:
        - write:space.setting:confluence
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: DELETE
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.