openapi: 3.1.0
info:
  title: Atlassian Admin Account Issue Field Configurations API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Issue Field Configurations
paths:
  /rest/api/3/fieldconfiguration/{id}:
    delete:
      deprecated: false
      description: Deletes a field configuration.<br><br>This operation can only delete configurations used in company-managed (classic) projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeletefieldconfiguration
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Field Configuration
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates a field configuration. The name and the description provided in the request override the existing values.<br><br>This operation can only update configurations used in company-managed (classic) projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatefieldconfiguration
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Field Configuration
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/fieldconfiguration/{id}/fields:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of all fields for a configuration.<br><br>Only the fields from configurations used in company-managed (classic) projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetfieldconfigurationitems
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Field Configuration Items
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates fields in a field configuration. The properties of the field configuration fields provided override the existing values.<br><br>This operation can only update field configurations used in company-managed (classic) projects.<br><br>The operation can set the renderer for text fields to the default text renderer (`text-renderer`) or wiki style renderer (`wiki-renderer`). However, the renderer cannot be updated for fields using the autocomplete renderer (`autocomplete-rend[...]
      operationId: atlassianUpdatefieldconfigurationitems
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Field Configuration Items
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/fieldconfigurationscheme/mapping:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of field configuration issue type items.<br><br>Only items used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetfieldconfigurationschememappings
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Field Configuration Issue Type Items
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/fieldconfigurationscheme/project:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of field configuration schemes and, for each scheme, a list of the projects that use it.<br><br>The list is sorted by field configuration scheme ID. The first item contains the list of project IDs assigned to the default field configuration scheme.<br><br>Only field configuration schemes used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassi[...]
      operationId: atlassianGetfieldconfigurationschemeprojectmapping
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Field Configuration Schemes For Projects
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Assigns a field configuration scheme to a project. If the field configuration scheme ID is `null`, the operation assigns the default field configuration scheme.<br><br>Field configuration schemes can only be assigned to classic projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianAssignfieldconfigurationschemetoproject
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Assign Field Configuration Scheme To Project
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/fieldconfigurationscheme/{id}:
    delete:
      deprecated: false
      description: Deletes a field configuration scheme.<br><br>This operation can only delete field configuration schemes used in company-managed (classic) projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianDeletefieldconfigurationscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Field Configuration Scheme
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    put:
      deprecated: false
      description: Updates a field configuration scheme.<br><br>This operation can only update field configuration schemes used in company-managed (classic) projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianUpdatefieldconfigurationscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Update Field Configuration Scheme
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/fieldconfigurationscheme/{id}/mapping:
    put:
      deprecated: false
      description: Assigns issue types to field configurations on field configuration scheme.<br><br>This operation can only modify field configuration schemes used in company-managed (classic) projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianSetfieldconfigurationschememapping
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Assign Issue Types To Field Configurations
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field-configuration-scheme:jira
        - read:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/fieldconfigurationscheme/{id}/mapping/delete:
    post:
      deprecated: false
      description: Removes issue types from the field configuration scheme.<br><br>This operation can only modify field configuration schemes used in company-managed (classic) projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianRemoveissuetypesfromglobalfieldconfigurationscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Remove Issue Types From Field Configuration Scheme
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/fieldconfiguration:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of field configurations. The list can be for all field configurations or a subset determined by any combination of these criteria:<br><br> *  a list of field configuration item IDs.<br> *  whether the field configuration is a default.<br> *  whether the field configuration name or description contains a query string.<br><br>Only field configurations used in company-managed (classic) projects are returned.<br><br>**[Permissions](#permissi[...]
      operationId: atlassianGetallfieldconfigurations
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get All Field Configurations
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    post:
      deprecated: false
      description: Creates a field configuration. The field configuration is created with the same field properties as the default configuration, with all the fields being optional.<br><br>This operation can only create configurations for use in company-managed (classic) projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreatefieldconfiguration
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Field Configuration
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field-configuration:jira
        - write:field-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
  /rest/api/3/fieldconfigurationscheme:
    get:
      deprecated: false
      description: Returns a [paginated](#pagination) list of field configuration schemes.<br><br>Only field configuration schemes used in classic projects are returned.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianGetallfieldconfigurationschemes
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get All Field Configuration Schemes
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
    post:
      deprecated: false
      description: Creates a field configuration scheme.<br><br>This operation can only create field configuration schemes used in company-managed (classic) projects.<br><br>**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
      operationId: atlassianCreatefieldconfigurationscheme
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Create Field Configuration Scheme
      tags:
      - Issue Field Configurations
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:field-configuration-scheme:jira
        - read:field-configuration-scheme:jira
        state: Beta
      x-atlassian-connect-scope: ADMIN
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.