openapi: 3.1.0
info:
  title: Atlassian Admin Account Myself API
  description: The Atlassian Admin API provides programmatic access to manage Atlassian organizations, users, domains, policies, and events. It enables administrators to automate organization management tasks, integrate with identity providers, and ensure appropriate access to Atlassian products.
  version: 1.0.0
  contact:
    name: Atlassian Developer
    url: https://developer.atlassian.com/cloud/admin/
  license:
    name: Atlassian Developer Terms
    url: https://developer.atlassian.com/platform/marketplace/atlassian-developer-terms/
  x-logo:
    url: https://wac-cdn.atlassian.com/assets/img/favicons/atlassian/favicon.png
servers:
- url: https://api.atlassian.com
  description: Atlassian Cloud API
security:
- bearerAuth: []
- oauth2: []
tags:
- name: Myself
paths:
  /rest/api/3/mypreferences/locale:
    delete:
      deprecated: true
      description: Deprecated, use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API instead.<br><br>Deletes the locale of the user, which restores the default setting.<br><br>**[Permissions](#permissions) required:** Permission to access Jira.
      operationId: atlassianDeletelocale
      security:
      - basicAuth: []
      summary: Atlassian Delete Locale
      tags:
      - Myself
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: INACCESSIBLE
    get:
      deprecated: false
      description: Returns the locale for the user.<br><br>If the user has no language preference set (which is the default setting) or this resource is accessed anonymous, the browser locale detected by Jira is returned. Jira detects the browser locale using the *Accept-Language* header in the request. However, if this doesn't match a locale available Jira, the site default locale is returned.<br><br>This operation can be accessed anonymously.<br><br>**[Permissions](#permissions) required:** No[...]
      operationId: atlassianGetlocale
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      - {}
      summary: Atlassian Get Locale
      tags:
      - Myself
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ACT_AS_USER
    put:
      deprecated: true
      description: Deprecated, use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API instead.<br><br>Sets the locale of the user. The locale must be one supported by the instance of Jira.<br><br>**[Permissions](#permissions) required:** Permission to access Jira.
      operationId: atlassianSetlocale
      security:
      - basicAuth: []
      summary: Atlassian Set Locale
      tags:
      - Myself
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-connect-scope: INACCESSIBLE
  /rest/api/3/mypreferences:
    delete:
      deprecated: false
      description: Deletes a preference of the user, which restores the default value of system defined settings.<br><br>Note that these keys are deprecated:<br><br> *  *jira.user.locale* The locale of the user. By default, not set. The user takes the instance locale.<br> *  *jira.user.timezone* The time zone of the user. By default, not set. The user takes the instance timezone.<br><br>Use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-accou[...]
      operationId: atlassianRemovepreference
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Delete Preference
      tags:
      - Myself
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - delete:user-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ACT_AS_USER
    get:
      deprecated: false
      description: Returns the value of a preference of the current user.<br><br>Note that these keys are deprecated:<br><br> *  *jira.user.locale* The locale of the user. By default this is not set and the user takes the locale of the instance.<br> *  *jira.user.timezone* The time zone of the user. By default this is not set and the user takes the timezone of the instance.<br><br>These system preferences keys will be deprecated by 15/07/2024. You can still retrieve these keys, but it will not h[...]
      operationId: atlassianGetpreference
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Get Preference
      tags:
      - Myself
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - read:user-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ACT_AS_USER
    put:
      deprecated: false
      description: 'Creates a preference for the user or updates a preference''s value by sending a plain text string. For example, `false`. An arbitrary preference can be created with the value containing up to 255 characters. In addition, the following keys define system preferences that can be set or created:<br><br> *  *user.notifications.mimetype* The mime type used in notifications sent to the user. Defaults to `html`.<br> *  *user.default.share.private* Whether new [ filters](https://conf[...]'
      operationId: atlassianSetpreference
      security:
      - basicAuth: []
      - OAuth2:
        - manage:jira-configuration
      summary: Atlassian Set Preference
      tags:
      - Myself
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - manage:jira-configuration
        state: Current
      - scheme: OAuth2
        scopes:
        - write:user-configuration:jira
        state: Beta
      x-atlassian-connect-scope: ACT_AS_USER
  /rest/api/3/myself:
    get:
      deprecated: false
      description: Returns details for the current user.<br><br>**[Permissions](#permissions) required:** Permission to access Jira.
      operationId: atlassianGetcurrentuser
      security:
      - basicAuth: []
      - OAuth2:
        - read:jira-user
      summary: Atlassian Get Current User
      tags:
      - Myself
      x-atlassian-data-security-policy:
      - app-access-rule-exempt: true
      x-atlassian-oauth2-scopes:
      - scheme: OAuth2
        scopes:
        - read:jira-user
        state: Current
      - scheme: OAuth2
        scopes:
        - read:application-role:jira
        - read:group:jira
        - read:user:jira
        - read:avatar:jira
        state: Beta
      x-atlassian-connect-scope: READ
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
      description: Use an Atlassian API key as a Bearer token. Create API keys at https://admin.atlassian.com.
    oauth2:
      type: oauth2
      description: OAuth 2.0 authorization for Atlassian Cloud APIs.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.atlassian.com/authorize
          tokenUrl: https://auth.atlassian.com/oauth/token
          scopes:
            read:org:admin: Read organization information.
            write:org:admin: Modify organization settings.
            read:user:admin: Read user information.
            write:user:admin: Modify user accounts.
            read:policy:admin: Read organization policies.
            write:policy:admin: Modify organization policies.
            read:event:admin: Read organization events.